/**
 * Asuryani.
 *
 * Generated by tools/import_catalogue.py from the New Recruit catalogue,
 * which tracks Kill Team 2018 including errata and the Elites and Commanders
 * expansions. Do not hand-edit: re-run the importer instead.
 *
 * 19 models, 37 weapons.
 *
 * Ability text is imported as prose. Machine-readable rules are tagged
 * separately, by hand, in module/rules/ - deciding what an ability does is a
 * judgement call and is not safe to automate.
 */

export const ASURYANI_WEAPONS = [
  { key: "aml-starshot-missile", name: "AML - Starshot Missile", points: 0, range: "48\"", weaponType: "heavy", attacks: "1", strength: "8", ap: -2, damage: "D6", abilities: "" },
  { key: "aml-sunburst-missile", name: "AML - Sunburst Missile", points: 0, range: "48\"", weaponType: "heavy", attacks: "D6", strength: "4", ap: -1, damage: "1", abilities: "" },
  { key: "avenger-shuriken-catapult", name: "Avenger shuriken catapult", points: 0, range: "18\"", weaponType: "assault", attacks: "2", strength: "4", ap: 0, damage: "1", abilities: "Each time you make a wound rolll of 6+ for this weapon, that hit is resolved with an AP of -3." },
  { key: "bright-lance", name: "Bright lance", points: 4, range: "36\"", weaponType: "heavy", attacks: "1", strength: "8", ap: -4, damage: "D6", abilities: "" },
  { key: "d-scythe", name: "D-scythe", points: 0, range: "8\"", weaponType: "assault", attacks: "D3", strength: "10", ap: -4, damage: "1", abilities: "This weapon automatically hits its target." },
  { key: "flamer", name: "Flamer", points: 3, range: "8\"", weaponType: "assault", attacks: "D6", strength: "4", ap: 0, damage: "1", abilities: "This weapon automatically hits its target." },
  { key: "fusion-gun", name: "Fusion gun", points: 3, range: "12\"", weaponType: "assault", attacks: "1", strength: "8", ap: -4, damage: "D6", abilities: "If the target is within half range of this weapon, roll two dice when inflicting damage with it and discard the lowest result." },
  { key: "fusion-pistol", name: "Fusion pistol", points: 0, range: "6\"", weaponType: "pistol", attacks: "1", strength: "8", ap: -4, damage: "D6", abilities: "" },
  { key: "plasma-grenade", name: "Plasma grenade", points: 0, range: "6\"", weaponType: "grenade", attacks: "D6", strength: "4", ap: -1, damage: "1", abilities: "" },
  { key: "ranger-long-rifle", name: "Ranger long rifle", points: 0, range: "36\"", weaponType: "heavy", attacks: "1", strength: "4", ap: 0, damage: "1", abilities: "A model firing a Ranger Long Rifle does not suffer the penalty to hit for the target being at long range. Each time you roll a wound roll of 6+ for this weapon, it inflicts one mortal wound in addition to any other damage." },
  { key: "scatter-laser", name: "Scatter laser", points: 2, range: "36\"", weaponType: "heavy", attacks: "4", strength: "6", ap: 0, damage: "1", abilities: "" },
  { key: "scorpion-s-claw-ranged", name: "Scorpion's claw - ranged", points: 0, range: "12\"", weaponType: "assault", attacks: "2", strength: "4", ap: 0, damage: "1", abilities: "Each time you make a wound roll of 6+ for this weapon, that hit is resolved with an AP of -3." },
  { key: "shuriken-cannon", name: "Shuriken cannon", points: 2, range: "24\"", weaponType: "assault", attacks: "3", strength: "6", ap: 0, damage: "1", abilities: "Each time you make a wound roll of 6+ for this weapon, that hit is resolved with an AP of -3." },
  { key: "shuriken-catapult", name: "Shuriken catapult", points: 0, range: "12\"", weaponType: "assault", attacks: "2", strength: "4", ap: 0, damage: "1", abilities: "Each time you make a wound roll of 6+ for this weapon, that hit is resolved with an AP of -3." },
  { key: "shuriken-pistol", name: "Shuriken pistol", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "4", ap: 0, damage: "1", abilities: "Each time you make a wound roll of 6+ for this weapon, that hit is resolved with an AP of -3." },
  { key: "singing-spear-ranged", name: "Singing spear (Ranged)", points: 0, range: "12\"", weaponType: "assault", attacks: "1", strength: "9", ap: 0, damage: "D3", abilities: "This weapon always wounds on a roll of 2+." },
  { key: "starcannon", name: "Starcannon", points: 3, range: "36\"", weaponType: "heavy", attacks: "2", strength: "6", ap: -3, damage: "D3", abilities: "" },
  { key: "voidbringer", name: "Voidbringer", points: 0, range: "48\"", weaponType: "heavy", attacks: "1", strength: "4", ap: -3, damage: "3", abilities: "A model firing this weapon does not suffer the penalty to hit rolls for the target being at long range. This weapon wounds on a 2+. Each time you roll a wound roll of 6+ for this weapon, it inflicts a mortal wound in addition to any other damage." },
  { key: "wraithcannon", name: "Wraithcannon", points: 0, range: "12\"", weaponType: "assault", attacks: "1", strength: "10", ap: -4, damage: "D6", abilities: "" },
  { key: "aeldari-blade", name: "Aeldari blade", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "You can re-roll failed hit rolls with this weapon." },
  { key: "biting-blade", name: "Biting blade", points: 3, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -1, damage: "2", abilities: "" },
  { key: "chainsword", name: "Chainsword", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "Each time the bearer fights, it can make one additional attack with this weapon." },
  { key: "diresword", name: "Diresword", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -2, damage: "1", abilities: "Each time you make a wound roll of 6+ for this weapon, the target suffers a mortal wound in addition to any other damage." },
  { key: "executioner", name: "Executioner", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+1", ap: -3, damage: "D3", abilities: "" },
  { key: "ghostaxe", name: "Ghostaxe", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -3, damage: "D3", abilities: "When attacking with this weapon, you must subtract 1 from the hit roll." },
  { key: "ghostswords", name: "Ghostswords", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+1", ap: -3, damage: "1", abilities: "Each time the bearer fights, it can make one additional attack with this weapon." },
  { key: "mirrorswords", name: "Mirrorswords", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -2, damage: "1", abilities: "You can re-roll failed hit rolls when attacking with this weapon." },
  { key: "power-blade", name: "Power blade", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -2, damage: "1", abilities: "" },
  { key: "power-glaive", name: "Power glaive", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+1", ap: -2, damage: "1", abilities: "" },
  { key: "power-sword", name: "Power sword", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -3, damage: "1", abilities: "" },
  { key: "scorpion-chainsword", name: "Scorpion chainsword", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+1", ap: 0, damage: "1", abilities: "" },
  { key: "scorpion-s-claw-melee", name: "Scorpion's claw - melee", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -3, damage: "D3", abilities: "" },
  { key: "singing-spear-melee", name: "Singing spear (Melee)", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "D3", abilities: "This weapon always wounds on a roll of 2+." },
  { key: "star-glaive", name: "Star glaive", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -3, damage: "D3", abilities: "When attacking with this weapon, you must subtract 1 from the hit roll." },
  { key: "witch-staff", name: "Witch staff", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "2", abilities: "" },
  { key: "witchblade", name: "Witchblade", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "D3", abilities: "This weapon always wounds on a roll of 2+." },
  { key: "wraithguard-fists", name: "Wraithguard fists", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "D3", abilities: "" }
];

export const ASURYANI_MODELS = [
  { key: "amallyn-shadowguide", name: "Amallyn Shadowguide", points: 30, maxNumber: "1", profile: { move: "7\"", ws: 3, bs: 2, strength: 3, toughness: 3, wounds: 3, attacks: 2, ld: 7, save: 5 }, keywords: "Asuryani, Aeldari, Warhost, Infantry, Ranger, Amallyn Shadowguide", wargear: "Power blade", specialisms: [], commander: false, abilities: [
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models.",
      "Battle Focus: If this model moves or Advances in its Movement phase, weapons (excluding Heavy weapons) are used as if the model had remained stationary."
    ] },
  { key: "autarch", name: "Autarch", points: 55, maxNumber: "1", profile: { move: "7\"", ws: 2, bs: 2, strength: 3, toughness: 3, wounds: 5, attacks: 4, ld: 9, save: 3 }, keywords: "Asuryani, Aeldari, Commander, Infantry, Warhost, Autarch", wargear: "", specialisms: [
      "Ferocity",
      "Leadership",
      "Logistics",
      "Melee",
      "Shooting",
      "Stealth",
      "Strategist"
    ], commander: true, abilities: [
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models.",
      "Battle Focus: If this model moves or Advances in its Movement phase, weapons (excluding Heavy weapons) are used as if the model had remained stationary."
    ] },
  { key: "dire-avenger", name: "Dire Avenger", points: 10, maxNumber: "-", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 1, ld: 8, save: 4 }, keywords: "Asuryani, Aeldari, Infantry, Aspect Warrior, Dire Avenger", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Medic",
      "Scout",
      "Veteran"
    ], commander: false, abilities: [
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models.",
      "Battle Focus: If this model moves or Advances in its Movement phase, weapons (excluding Heavy weapons) are used as if the model had remained stationary.",
      "Defence Tactics: When this model fires Overwatch, they successfully hit on a roll of 5 or 6."
    ] },
  { key: "dire-avenger-exarch", name: "Dire Avenger Exarch", points: 11, maxNumber: "1", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 2, attacks: 2, ld: 8, save: 4 }, keywords: "Asuryani, Aeldari, Infantry, Aspect Warrior, Dire Avenger", wargear: "Shimmershield & Power Glaive; Shuriken Pistol & Diresword; Shuriken Pistol & Power Glaive; Two Avenger Shuriken Catapults", specialisms: [
      "Combat",
      "Comms",
      "Medic",
      "Scout",
      "Veteran"
    ], commander: false, abilities: [
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models.",
      "Battle Focus: If this model moves or Advances in its Movement phase, weapons (excluding Heavy weapons) are used as if the model had remained stationary.",
      "Defence Tactics: When this model fires Overwatch, they successfully hit on a roll of 5 or 6."
    ] },
  { key: "farseer", name: "Farseer", points: 55, maxNumber: "1", profile: { move: "7\"", ws: 2, bs: 2, strength: 3, toughness: 3, wounds: 5, attacks: 2, ld: 9, save: 6 }, keywords: "Asuryani, Aeldari, Commander, Infantry, Psyker, Warhost, Farseer", wargear: "", specialisms: [
      "Leadership",
      "Logistics",
      "Psyker",
      "Strategist"
    ], commander: true, abilities: [
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models.",
      "Battle Focus: If this model moves or Advances in its Movement phase, weapons (excluding Heavy weapons) are used as if the model had remained stationary."
    ] },
  { key: "guardian-defender", name: "Guardian Defender", points: 7, maxNumber: "-", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 1, ld: 7, save: 5 }, keywords: "Asuryani, Aeldari, Warhost, Infantry, Guardian, Guardian Defender", wargear: "", specialisms: [
      "Comms",
      "Medic",
      "Scout",
      "Veteran"
    ], commander: false, abilities: [
      "Battle Focus: If this model moves or Advances in its Movement phase, weapons (excluding Heavy weapons) are used as if the model had remained stationary.",
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models."
    ] },
  { key: "heavy-weapons-platform", name: "Heavy Weapons Platform", points: 8, maxNumber: "1", profile: { move: "7\"", ws: 6, bs: 3, strength: 3, toughness: 3, wounds: 2, attacks: 1, ld: 7, save: 3 }, keywords: "Asuryani, Aeldari, Warhost, Infantry, Artillery, Guardian, Heavy Weapon Platform", wargear: "", specialisms: [], commander: false, abilities: [
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models.",
      "Battle Focus: If this model moves or Advances in its Movement phase, weapons (excluding Heavy weapons) are used as if the model had remained stationary."
    ] },
  { key: "howling-banshee", name: "Howling Banshee", points: 11, maxNumber: "-", profile: { move: "8\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 2, ld: 8, save: 4 }, keywords: "Asuryani, Aeldari, Aspect Warrior, Infantry, Howling Banshee", wargear: "Power sword", specialisms: [
      "Combat",
      "Comms",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Acrobatic: You can re-roll failed charge rolls for this model.",
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models.",
      "Battle Focus: If this model moves or Advances in its Movement phase, weapons (excluding Heavy weapons) are used as if the model had remained stationary."
    ] },
  { key: "howling-banshee-exarch", name: "Howling Banshee Exarch", points: 14, maxNumber: "1", profile: { move: "8\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 2, attacks: 3, ld: 8, save: 4 }, keywords: "Asuryani, Aeldari, Aspect Warrior, Infantry, Howling Banshee", wargear: "Executioner and shuriken pistol; Mirrorswords; Power sword and shuriken pistol", specialisms: [
      "Combat",
      "Comms",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Acrobatic: You can re-roll failed charge rolls for this model.",
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models.",
      "Battle Focus: If this model moves or Advances in its Movement phase, weapons (excluding Heavy weapons) are used as if the model had remained stationary."
    ] },
  { key: "illic-nightspear", name: "Illic Nightspear", points: 79, maxNumber: "1", profile: { move: "7\"", ws: 2, bs: 2, strength: 3, toughness: 3, wounds: 5, attacks: 4, ld: 9, save: 5 }, keywords: "Asuryani, Aeldari, Warhost, Alaitoc, Infantry, Ranger, Illic Nightspear", wargear: "Power sword; Voidbringer", specialisms: [], commander: false, abilities: [
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models.",
      "Battle Focus: If this model moves or Advances in its Movement phase, weapons (excluding Heavy weapons) are used as if the model had remained stationary."
    ] },
  { key: "ranger", name: "Ranger", points: 11, maxNumber: "-", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 1, ld: 7, save: 5 }, keywords: "Asuryani, Aeldari, Warhost, Infantry, Ranger", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Medic",
      "Sniper",
      "Veteran"
    ], commander: false, abilities: [
      "Battle Focus: If this model moves or Advances in its Movement phase, weapons (excluding Heavy weapons) are used as if the model had remained stationary.",
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models."
    ] },
  { key: "spiritseer", name: "Spiritseer", points: 61, maxNumber: "1", profile: { move: "7\"", ws: 2, bs: 2, strength: 3, toughness: 3, wounds: 4, attacks: 2, ld: 8, save: 6 }, keywords: "Asuryani, Aeldari, Spirit Host, Infantry, Psyker, Spiritseer", wargear: "Witch staff", specialisms: [
      "Leadership",
      "Melee",
      "Psyker",
      "Stealth",
      "Strategist"
    ], commander: true, abilities: [
      "Battle Focus: If this model moves or Advances in its Movement phase, weapons (excluding Heavy weapons) are used as if the model had remained stationary.",
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models."
    ] },
  { key: "storm-guardian", name: "Storm Guardian", points: 6, maxNumber: "-", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 1, ld: 7, save: 5 }, keywords: "Asuryani, Aeldari, Warhost, Infantry, Guardian, Storm Guardian", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Medic",
      "Scout",
      "Veteran"
    ], commander: false, abilities: [
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models.",
      "Battle Focus: If this model moves or Advances in its Movement phase, weapons (excluding Heavy weapons) are used as if the model had remained stationary."
    ] },
  { key: "storm-guardian-gunner", name: "Storm Guardian Gunner", points: 7, maxNumber: "2", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 1, ld: 7, save: 5 }, keywords: "Asuryani, Aeldari, Warhost, Infantry, Guardian, Storm Guardian", wargear: "Shuriken Pistol & Aeldari Blade; Shuriken Pistol & Chainsword", specialisms: [
      "Combat",
      "Comms",
      "Medic",
      "Scout",
      "Veteran"
    ], commander: false, abilities: [
      "Battle Focus: If this model moves or Advances in its Movement phase, weapons (excluding Heavy weapons) are used as if the model had remained stationary.",
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models."
    ] },
  { key: "striking-scorpion", name: "Striking Scorpion", points: 12, maxNumber: "-", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 2, ld: 8, save: 3 }, keywords: "Asuryani, Aeldari, Aspect Warrior, Infantry, Striking Scorpion", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Scout",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models.",
      "Battle Focus: If this model moves or Advances in its Movement phase, weapons (excluding Heavy weapons) are used as if the model had remained stationary.",
      "Shadow Strike: Add 1 to hit rolls for attacks made by this model that target a model which is obscured or when there is intervening terrain."
    ] },
  { key: "striking-scorpion-exarch", name: "Striking Scorpion Exarch", points: 14, maxNumber: "-", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 2, attacks: 3, ld: 8, save: 3 }, keywords: "Asuryani, Aeldari, Aspect Warrior, Infantry, Striking Scorpion", wargear: "Biting blade; Scorpion's claw", specialisms: [
      "Combat",
      "Demolitions",
      "Scout",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models.",
      "Battle Focus: If this model moves or Advances in its Movement phase, weapons (excluding Heavy weapons) are used as if the model had remained stationary.",
      "Shadow Strike: Add 1 to hit rolls for attacks made by this model that target a model which is obscured or when there is intervening terrain."
    ] },
  { key: "warlock", name: "Warlock", points: 20, maxNumber: "1", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 2, attacks: 2, ld: 8, save: 6 }, keywords: "Asuryani, Aeldari, Commander, Infantry, Psyker, Warlock, Warhost", wargear: "", specialisms: [
      "Logistics",
      "Melee",
      "Psyker",
      "Shooting"
    ], commander: true, abilities: [
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models.",
      "Battle Focus: If this model moves or Advances in its Movement phase, weapons (excluding Heavy weapons) are used as if the model had remained stationary."
    ] },
  { key: "wraithblade", name: "Wraithblade", points: 36, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 3, strength: 5, toughness: 6, wounds: 3, attacks: 2, ld: 9, save: 3 }, keywords: "Asuryani, Aeldari, Spirit Host, Infantry, Wraith Construct, Wraithblade", wargear: "Ghostaxe and forceshield; Ghostswords", specialisms: [
      "Combat",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models.",
      "Ghost Warrior: This model cannot gain experience."
    ] },
  { key: "wraithguard", name: "Wraithguard", points: 41, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 3, strength: 5, toughness: 6, wounds: 3, attacks: 1, ld: 9, save: 3 }, keywords: "Asuryani, Aeldari, Spirit Host, Infantry, Wraith Construct, Wraithguard", wargear: "D-scythe; Wraithcannon; Wraithguard fists", specialisms: [
      "Demolitions",
      "Heavy",
      "Veteran"
    ], commander: false, abilities: [
      "Ancient Doom: You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3\" of any SLAANESH models.",
      "Ghost Warrior: This model cannot gain experience."
    ] }
];

const FACTION = "Asuryani";

export const ASURYANI_ITEMS = ASURYANI_WEAPONS.map(w => ({ ...w, itemType: "weapon", faction: FACTION }));

export const ASURYANI_MODEL_ITEMS = ASURYANI_MODELS.map(m => ({ ...m, itemType: "model", faction: FACTION, rules: [] }));
