/**
 * Chaos Daemons.
 *
 * Generated by tools/import_catalogue.py from the New Recruit catalogue,
 * which tracks Kill Team 2018 including errata and the Elites and Commanders
 * expansions. Do not hand-edit: re-run the importer instead.
 *
 * 16 models, 4 weapons.
 *
 * Ability text is imported as prose. Machine-readable rules are tagged
 * separately, by hand, in module/rules/ - deciding what an ability does is a
 * judgement call and is not safe to automate.
 */

export const CHAOS_DAEMONS_WEAPONS = [
  { key: "coruscating-flames", name: "Coruscating Flames", points: 0, range: "18\"", weaponType: "assault", attacks: "2", strength: "User", ap: 0, damage: "1", abilities: "" },
  { key: "hellblade", name: "Hellblade", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -3, damage: "1", abilities: "Any attacks with a wound roll of 6+ for this weapon have a Damage characteristic of 2 instead of 1." },
  { key: "piercing-claws", name: "Piercing Claws", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "1", abilities: "Each time you make a wound roll of 6+ for this weapon, that hit is resolved with an AP of -4 instead of -1." },
  { key: "plaguesword", name: "Plaguesword", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "You can re-roll wound rolls of 1 for this weapon." }
];

export const CHAOS_DAEMONS_MODELS = [
  { key: "alluress", name: "Alluress", points: 8, maxNumber: "1", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 3, ld: 7, save: 6 }, keywords: "Chaos Daemons, Chaos, Slaanesh, Infantry, Daemon, Daemonette", wargear: "", specialisms: [
      "Combat",
      "Scout",
      "Veteran"
    ], commander: false, abilities: [
      "Daemonic: This model has a 5+ invulnerable save.",
      "Quicksilver Swiftness: A model with this ability can be chosen to fight in the Hammer of Wrath section of the Fight phase even if they have not charged in that battle round."
    ] },
  { key: "bloodletter", name: "Bloodletter", points: 7, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 3, wounds: 1, attacks: 1, ld: 7, save: 6 }, keywords: "Chaos Daemons, Chaos, Khorne, Infantry, Daemon, Bloodletter", wargear: "", specialisms: [
      "Combat",
      "Veteran"
    ], commander: false, abilities: [
      "Daemonic: This model has a 5+ invulnerable save.",
      "Unstoppable Ferocity: You can add 1 to the Attacks and Strength characteristics of a model with this ability in a battle round in which they charged."
    ] },
  { key: "bloodletter-hornblower", name: "Bloodletter Hornblower", points: 8, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 3, wounds: 1, attacks: 1, ld: 7, save: 6 }, keywords: "Chaos Daemons, Chaos, Khorne, Infantry, Daemon, Bloodletter", wargear: "Instrument of Khorne", specialisms: [
      "Combat",
      "Comms",
      "Veteran"
    ], commander: false, abilities: [
      "Daemonic: This model has a 5+ invulnerable save.",
      "Unstoppable Ferocity: You can add 1 to the Attacks and Strength characteristics of a model with this ability in a battle round in which they charged."
    ] },
  { key: "bloodletter-icon-bearer", name: "Bloodletter Icon Bearer", points: 8, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 3, wounds: 1, attacks: 1, ld: 7, save: 6 }, keywords: "Chaos Daemons, Chaos, Khorne, Infantry, Daemon, Bloodletter", wargear: "Icon of Khorne", specialisms: [
      "Combat",
      "Comms",
      "Veteran"
    ], commander: false, abilities: [
      "Daemonic: This model has a 5+ invulnerable save.",
      "Unstoppable Ferocity: You can add 1 to the Attacks and Strength characteristics of a model with this ability in a battle round in which they charged."
    ] },
  { key: "bloodreaper", name: "Bloodreaper", points: 8, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 3, wounds: 1, attacks: 2, ld: 7, save: 6 }, keywords: "Chaos Daemons, Chaos, Khorne, Infantry, Daemon, Bloodletter", wargear: "", specialisms: [
      "Combat",
      "Veteran"
    ], commander: false, abilities: [
      "Daemonic: This model has a 5+ invulnerable save.",
      "Unstoppable Ferocity: You can add 1 to the Attacks and Strength characteristics of a model with this ability in a battle round in which they charged."
    ] },
  { key: "daemonette", name: "Daemonette", points: 7, maxNumber: "-", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 2, ld: 7, save: 6 }, keywords: "Chaos Daemons, Chaos, Slaanesh, Infantry, Daemon, Daemonette", wargear: "", specialisms: [
      "Combat",
      "Scout",
      "Veteran"
    ], commander: false, abilities: [
      "Daemonic: This model has a 5+ invulnerable save.",
      "Quicksilver Swiftness: A model with this ability can be chosen to fight in the Hammer of Wrath section of the Fight phase even if they have not charged in that battle round."
    ] },
  { key: "daemonette-hornblower", name: "Daemonette Hornblower", points: 8, maxNumber: "1", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 2, ld: 7, save: 6 }, keywords: "Chaos Daemons, Chaos, Slaanesh, Infantry, Daemon, Daemonette", wargear: "Instrument of Slaanesh", specialisms: [
      "Combat",
      "Comms",
      "Scout",
      "Veteran"
    ], commander: false, abilities: [
      "Daemonic: This model has a 5+ invulnerable save.",
      "Quicksilver Swiftness: A model with this ability can be chosen to fight in the Hammer of Wrath section of the Fight phase even if they have not charged in that battle round."
    ] },
  { key: "daemonette-icon-bearer", name: "Daemonette Icon Bearer", points: 8, maxNumber: "1", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 2, ld: 7, save: 6 }, keywords: "Chaos Daemons, Chaos, Slaanesh, Infantry, Daemon, Daemonette", wargear: "Icon of Slaanesh", specialisms: [
      "Combat",
      "Comms",
      "Scout",
      "Veteran"
    ], commander: false, abilities: [
      "Daemonic: This model has a 5+ invulnerable save.",
      "Quicksilver Swiftness: A model with this ability can be chosen to fight in the Hammer of Wrath section of the Fight phase even if they have not charged in that battle round."
    ] },
  { key: "iridescent-horror", name: "Iridescent Horror", points: 13, maxNumber: "1", profile: { move: "6\"", ws: 4, bs: 4, strength: 3, toughness: 3, wounds: 1, attacks: 2, ld: 7, save: 6 }, keywords: "Chaos Daemons, Chaos, Tzeentch, Infantry, Daemon, Horror", wargear: "", specialisms: [
      "Demolitions",
      "Veteran"
    ], commander: false, abilities: [
      "Ephemeral Daemons: This model has an invulnerable save of 4+. Blue Horrors instead have an invulnerable save of 5+. Pairs of Brimstone Horrors instead have an invulnerable save of 6+."
    ] },
  { key: "pink-horror", name: "Pink Horror", points: 12, maxNumber: "-", profile: { move: "6\"", ws: 4, bs: 4, strength: 3, toughness: 3, wounds: 1, attacks: 1, ld: 7, save: 6 }, keywords: "Chaos Daemons, Chaos, Tzeentch, Infantry, Daemon, Horror", wargear: "", specialisms: [
      "Demolitions",
      "Veteran"
    ], commander: false, abilities: [
      "Ephemeral Daemons: This model has an invulnerable save of 4+. Blue Horrors instead have an invulnerable save of 5+. Pairs of Brimstone Horrors instead have an invulnerable save of 6+."
    ] },
  { key: "pink-horror-hornblower", name: "Pink Horror Hornblower", points: 13, maxNumber: "1", profile: { move: "6\"", ws: 4, bs: 4, strength: 3, toughness: 3, wounds: 1, attacks: 1, ld: 7, save: 6 }, keywords: "Chaos Daemons, Chaos, Tzeentch, Infantry, Daemon, Horror", wargear: "Instrument of Tzeentch", specialisms: [
      "Comms",
      "Demolitions",
      "Veteran"
    ], commander: false, abilities: [
      "Ephemeral Daemons: This model has an invulnerable save of 4+. Blue Horrors instead have an invulnerable save of 5+. Pairs of Brimstone Horrors instead have an invulnerable save of 6+."
    ] },
  { key: "pink-horror-icon-bearer", name: "Pink Horror Icon Bearer", points: 13, maxNumber: "1", profile: { move: "6\"", ws: 4, bs: 4, strength: 3, toughness: 3, wounds: 1, attacks: 1, ld: 7, save: 6 }, keywords: "Chaos Daemons, Chaos, Tzeentch, Infantry, Daemon, Horror", wargear: "Icon of Tzeentch", specialisms: [
      "Comms",
      "Demolitions",
      "Veteran"
    ], commander: false, abilities: [
      "Ephemeral Daemons: This model has an invulnerable save of 4+. Blue Horrors instead have an invulnerable save of 5+. Pairs of Brimstone Horrors instead have an invulnerable save of 6+."
    ] },
  { key: "plaguebearer", name: "Plaguebearer", points: 7, maxNumber: "-", profile: { move: "5\"", ws: 4, bs: 4, strength: 4, toughness: 4, wounds: 1, attacks: 1, ld: 7, save: 6 }, keywords: "Chaos Daemons, Chaos, Nurgle, Infantry, Daemon, Plaguebearer", wargear: "", specialisms: [
      "Combat",
      "Veteran"
    ], commander: false, abilities: [
      "Daemonic: This model has a 5+ invulnerable save.",
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound."
    ] },
  { key: "plaguebearer-hornblower", name: "Plaguebearer Hornblower", points: 8, maxNumber: "1", profile: { move: "5\"", ws: 4, bs: 4, strength: 4, toughness: 4, wounds: 1, attacks: 1, ld: 7, save: 6 }, keywords: "Chaos Daemons, Chaos, Nurgle, Infantry, Daemon, Plaguebearer", wargear: "Instrument of Nurgle", specialisms: [
      "Combat",
      "Comms",
      "Veteran"
    ], commander: false, abilities: [
      "Daemonic: This model has a 5+ invulnerable save.",
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound."
    ] },
  { key: "plaguebearer-icon-bearer", name: "Plaguebearer Icon Bearer", points: 8, maxNumber: "1", profile: { move: "5\"", ws: 4, bs: 4, strength: 4, toughness: 4, wounds: 1, attacks: 1, ld: 7, save: 6 }, keywords: "Chaos Daemons, Chaos, Nurgle, Infantry, Daemon, Plaguebearer", wargear: "Icon of Nurgle", specialisms: [
      "Combat",
      "Comms",
      "Veteran"
    ], commander: false, abilities: [
      "Daemonic: This model has a 5+ invulnerable save.",
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound."
    ] },
  { key: "plagueridden", name: "Plagueridden", points: 8, maxNumber: "1", profile: { move: "5\"", ws: 4, bs: 4, strength: 4, toughness: 4, wounds: 1, attacks: 2, ld: 7, save: 6 }, keywords: "Chaos Daemons, Chaos, Nurgle, Infantry, Daemon, Plaguebearer", wargear: "", specialisms: [
      "Combat",
      "Veteran"
    ], commander: false, abilities: [
      "Daemonic: This model has a 5+ invulnerable save.",
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound."
    ] }
];

const FACTION = "Chaos Daemons";

export const CHAOS_DAEMONS_ITEMS = CHAOS_DAEMONS_WEAPONS.map(w => ({ ...w, itemType: "weapon", faction: FACTION }));

export const CHAOS_DAEMONS_MODEL_ITEMS = CHAOS_DAEMONS_MODELS.map(m => ({ ...m, itemType: "model", faction: FACTION, rules: [] }));
