/**
 * Death Guard.
 *
 * Generated by tools/import_catalogue.py from the New Recruit catalogue,
 * which tracks Kill Team 2018 including errata and the Elites and Commanders
 * expansions. Do not hand-edit: re-run the importer instead.
 *
 * 16 models, 32 weapons.
 *
 * Ability text is imported as prose. Machine-readable rules are tagged
 * separately, by hand, in module/rules/ - deciding what an ability does is a
 * judgement call and is not safe to automate.
 */

export const DEATH_GUARD_WEAPONS = [
  { key: "blight-grenade", name: "Blight grenade", points: 0, range: "6\"", weaponType: "grenade", attacks: "D6", strength: "3", ap: 0, damage: "1", abilities: "You can re-roll wound rolls of 1 for this weapon." },
  { key: "blight-launcher", name: "Blight launcher", points: 7, range: "24\"", weaponType: "assault", attacks: "2", strength: "6", ap: -2, damage: "D3", abilities: "You can re-roll wound rolls of 1 for this weapon." },
  { key: "bolt-pistol", name: "Bolt pistol", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "boltgun", name: "Boltgun", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "1", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "combi-bolter", name: "Combi-bolter", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "2", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "combi-weapon", name: "Combi-weapon", points: 0, range: "-", weaponType: "assault", attacks: "1", strength: "", ap: 0, damage: "-", abilities: "When attacking with this weapon, choose one or both of the profiles below. If you choose both, subtract 1 from all hit rolls made for this weapon." },
  { key: "flamer", name: "Flamer", points: 0, range: "8\"", weaponType: "assault", attacks: "D6", strength: "4", ap: 0, damage: "1", abilities: "This weapon automatically hits its target." },
  { key: "hyper-blight-grenade", name: "Hyper blight grenade", points: 0, range: "6\"", weaponType: "grenade", attacks: "D6", strength: "4", ap: 0, damage: "2", abilities: "You can re-roll wound rolls of 1 for this weapon. Each wound roll of 6+ made for this weapon inflicts a mortal wound on the target in addition to any other damage." },
  { key: "injector-pistol", name: "Injector Pistol", points: 0, range: "3\"", weaponType: "pistol", attacks: "1", strength: "4", ap: -1, damage: "D6", abilities: "You can re-roll wound rolls of 1 for this weapon." },
  { key: "krak-grenade", name: "Krak grenade", points: 0, range: "6\"", weaponType: "grenade", attacks: "1", strength: "6", ap: -1, damage: "D3", abilities: "" },
  { key: "meltagun", name: "Meltagun", points: 3, range: "12\"", weaponType: "assault", attacks: "1", strength: "8", ap: -4, damage: "D6", abilities: "If the target is within half range of this weapon, roll two dice when inflicting damage with it and discard the lowest result." },
  { key: "plague-belcher", name: "Plague belcher", points: 3, range: "9\"", weaponType: "assault", attacks: "D6", strength: "4", ap: 0, damage: "1", abilities: "You can re-roll wound rolls of 1 for this weapon. This weapon automatically hits its target." },
  { key: "plague-spewer", name: "Plague spewer", points: 4, range: "9\"", weaponType: "heavy", attacks: "D6", strength: "5", ap: -1, damage: "1", abilities: "You can re-roll wound rolls of 1 for this weapon. This weapon automatically hits its target." },
  { key: "plague-sprayer", name: "Plague sprayer", points: 0, range: "9\"", weaponType: "assault", attacks: "D6", strength: "2D6", ap: -3, damage: "3", abilities: "This weapon automatically hits its target. Roll to determine the Strength of this weapon after selecting its target(s). You can re-roll wound rolls of 1 for this weapon." },
  { key: "plaguespurt-gauntlet", name: "Plaguespurt gauntlet", points: 0, range: "6\"", weaponType: "pistol", attacks: "D6", strength: "3", ap: 0, damage: "1", abilities: "You can re-roll wound rolls of 1 for this weapon. This weapon automatically hits its target." },
  { key: "plasma-gun", name: "Plasma gun", points: 3, range: "24\"", weaponType: "rapidFire", attacks: "1", strength: "7", ap: -3, damage: "1", abilities: "This weapon can be supercharged bythe bearer before firing. If they do so, increase the Strength and Damage of the weapon by 1. On any unmodified hit rolls of 1 when firing supercharge, the bearer is taken out of action, after all of the weapon's shots have been resolved." },
  { key: "plasma-gun-standard", name: "Plasma gun - Standard", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "1", strength: "7", ap: -3, damage: "1", abilities: "" },
  { key: "plasma-gun-supercharge", name: "Plasma gun - Supercharge", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "1", strength: "8", ap: -3, damage: "2", abilities: "On an unmodified hit roll of 1, the bearer is slain once all of this weapon's shots have been resolved." },
  { key: "plasma-pistol-standard", name: "Plasma pistol - Standard", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "7", ap: -3, damage: "1", abilities: "" },
  { key: "plasma-pistol-supercharge", name: "Plasma pistol - Supercharge", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "8", ap: -3, damage: "2", abilities: "On an unmodified hit roll of 1, the bearer is slain once all of this weapon's shots have been resolved." },
  { key: "reaper-autocannon", name: "Reaper autocannon", points: 5, range: "36\"", weaponType: "heavy", attacks: "4", strength: "7", ap: -1, damage: "1", abilities: "" },
  { key: "balesword", name: "Balesword", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -3, damage: "1", abilities: "You can re-roll wound rolls of 1 for this weapon." },
  { key: "bubotic-axe", name: "Bubotic axe", points: 2, range: "Melee", weaponType: "melee", attacks: "1", strength: "+1", ap: -2, damage: "1", abilities: "You can re-roll wound rolls of 1 for this weapon." },
  { key: "flail-of-corruption", name: "Flail of corruption", points: 4, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -2, damage: "1", abilities: "You can re-roll wound rolls of 1 for this weapon. Make D3 hit rolls each time you attack with this weapon." },
  { key: "great-plague-cleaver", name: "Great plague cleaver", points: 4, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -3, damage: "D6", abilities: "You can re-roll wound rolls of 1 for this weapon. When attacking with this weapon, you must subtract 1 from the hit roll." },
  { key: "improvised-weapon", name: "Improvised Weapon", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "" },
  { key: "mace-of-contagion", name: "Mace of contagion", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -1, damage: "3", abilities: "You can re-roll wound rolls of 1 for this weapon. When attacking with this weapon, you must subtract 1 from the hit roll." },
  { key: "manreaper", name: "Manreaper", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+3", ap: -3, damage: "D3", abilities: "You can re-roll wound rolls of 1 for this weapon." },
  { key: "plague-knife", name: "Plague knife", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "You can re-roll wound rolls of 1 for this weapon." },
  { key: "plaguereaper", name: "Plaguereaper", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -3, damage: "3", abilities: "You can re-roll wound rolls of 1 for this weapon." },
  { key: "plaguesword", name: "Plaguesword", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "You can re-roll failed wound rolls for this weapon." },
  { key: "power-fist", name: "Power fist", points: 4, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -3, damage: "D3", abilities: "When attacking with this weapon, you must subtract 1 from the hit roll." }
];

export const DEATH_GUARD_MODELS = [
  { key: "biologus-putrifier", name: "Biologus Putrifier", points: 50, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 5, wounds: 4, attacks: 3, ld: 8, save: 3 }, keywords: "Death Guard, Chaos, Nurgle, Infantry, Biologus Putrifier", wargear: "Hyper blight grenades; Injector Pistol; Krak grenades", specialisms: [
      "Fortitude",
      "Logistics",
      "Melee",
      "Shooting",
      "Strength"
    ], commander: true, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "blightlord-champion", name: "Blightlord Champion", points: 41, maxNumber: "1", profile: { move: "4\"", ws: 3, bs: 3, strength: 4, toughness: 5, wounds: 2, attacks: 3, ld: 9, save: 2 }, keywords: "Death Guard, Chaos, Nurgle, Heretic Astartes, Infantry, Terminator, Blightlord Terminator", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound.",
      "Cataphractii Armour: This model has a 4+ invulnerable save, but you must halve the result of the dice rolled when determining how far it Advances."
    ] },
  { key: "blightlord-fighter", name: "Blightlord Fighter", points: 41, maxNumber: "2", profile: { move: "4\"", ws: 3, bs: 3, strength: 4, toughness: 5, wounds: 2, attacks: 2, ld: 8, save: 2 }, keywords: "Death Guard, Chaos, Nurgle, Heretic Astartes, Infantry, Terminator, Blightlord Terminator", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound.",
      "Cataphractii Armour: This model has a 4+ invulnerable save, but you must halve the result of the dice rolled when determining how far it Advances."
    ] },
  { key: "blightlord-gunner", name: "Blightlord Gunner", points: 41, maxNumber: "2", profile: { move: "4\"", ws: 3, bs: 3, strength: 4, toughness: 5, wounds: 2, attacks: 2, ld: 8, save: 2 }, keywords: "Death Guard, Chaos, Nurgle, Heretic Astartes, Infantry, Terminator, Blightlord Terminator", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Heavy",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound.",
      "Cataphractii Armour: This model has a 4+ invulnerable save, but you must halve the result of the dice rolled when determining how far it Advances."
    ] },
  { key: "blightlord-terminator", name: "Blightlord Terminator", points: 40, maxNumber: "-", profile: { move: "4\"", ws: 3, bs: 3, strength: 4, toughness: 5, wounds: 2, attacks: 2, ld: 8, save: 2 }, keywords: "Death Guard, Chaos, Nurgle, Heretic Astartes, Infantry, Terminator, Blightlord Terminator", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound.",
      "Cataphractii Armour: This model has a 4+ invulnerable save, but you must halve the result of the dice rolled when determining how far it Advances."
    ] },
  { key: "deathshroud-champion", name: "Deathshroud Champion", points: 55, maxNumber: "-", profile: { move: "4\"", ws: 3, bs: 3, strength: 5, toughness: 5, wounds: 2, attacks: 4, ld: 9, save: 2 }, keywords: "Death Guard, Chaos, Nurgle, Heretic Astartes, Infantry, Terminator, Deathshroud Terminator", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "Cataphractii Armour: This model has a 4+ invulnerable save, but you must halve the result of the dice rolled when determining how far it Advances."
    ] },
  { key: "deathshroud-terminator", name: "Deathshroud Terminator", points: 50, maxNumber: "-", profile: { move: "4\"", ws: 3, bs: 3, strength: 5, toughness: 5, wounds: 2, attacks: 3, ld: 8, save: 2 }, keywords: "Death Guard, Chaos, Nurgle, Heretic Astartes, Infantry, Terminator, Deathshroud Terminator", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "Cataphractii Armour: This model has a 4+ invulnerable save, but you must halve the result of the dice rolled when determining how far it Advances."
    ] },
  { key: "foul-blightspawn", name: "Foul Blightspawn", points: 80, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 5, wounds: 4, attacks: 3, ld: 8, save: 3 }, keywords: "Death Guard, Chaos, Nurgle, Heretic Astartes, Commander, Infantry, Foul Blightspawn", wargear: "Plague sprayer", specialisms: [
      "Fortitude",
      "Logistics",
      "Melee",
      "Strength"
    ], commander: true, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "lord-of-contagion", name: "Lord of Contagion", points: 114, maxNumber: "1", profile: { move: "4\"", ws: 2, bs: 2, strength: 4, toughness: 5, wounds: 6, attacks: 4, ld: 9, save: 2 }, keywords: "Death Guard, Chaos, Nurgle, Heretic Astartes, Infantry, Terminator, Lord of Contagion", wargear: "", specialisms: [
      "Ferocity",
      "Fortitude",
      "Leadership",
      "Logistics",
      "Melee",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound.",
      "Cataphractii Armour: This model has a 4+ invulnerable save, but you must halve the result of the dice rolled when determining how far it Advances."
    ] },
  { key: "plague-champion", name: "Plague Champion", points: 15, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 5, wounds: 1, attacks: 2, ld: 8, save: 3 }, keywords: "Death Guard, Chaos, Nurgle, Heretic Astartes, Infantry, Plague Marine", wargear: "Plaguesword; Power fist", specialisms: [
      "Combat",
      "Demolitions",
      "Veteran"
    ], commander: false, abilities: [
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound.",
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "plague-marine", name: "Plague Marine", points: 14, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 5, wounds: 1, attacks: 1, ld: 7, save: 3 }, keywords: "Death Guard, Chaos, Nurgle, Heretic Astartes, Infantry, Plague Marine", wargear: "Icon of Despair", specialisms: [
      "Combat",
      "Demolitions",
      "Veteran"
    ], commander: false, abilities: [
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound.",
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "plague-marine-fighter", name: "Plague Marine Fighter", points: 15, maxNumber: "2", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 5, wounds: 1, attacks: 2, ld: 7, save: 3 }, keywords: "Death Guard, Chaos, Nurgle, Heretic Astartes, Infantry, Plague Marine", wargear: "Great plague cleaver; Mace of contagion and bubotic axe", specialisms: [
      "Combat",
      "Demolitions",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound.",
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "plague-marine-gunner", name: "Plague Marine Gunner", points: 15, maxNumber: "2", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 5, wounds: 1, attacks: 1, ld: 7, save: 3 }, keywords: "Death Guard, Chaos, Nurgle, Heretic Astartes, Infantry, Plague Marine", wargear: "Blight launcher; Meltagun; Plague belcher; Plague spewer", specialisms: [
      "Combat",
      "Demolitions",
      "Heavy",
      "Veteran"
    ], commander: false, abilities: [
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound.",
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "plague-surgeon", name: "Plague Surgeon", points: 45, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 5, wounds: 4, attacks: 3, ld: 8, save: 3 }, keywords: "Death Guard, Chaos, Nurgle, Heretic Astartes, Infantry, Plague Surgeon", wargear: "", specialisms: [
      "Fortitude",
      "Leadership",
      "Logistics",
      "Melee",
      "Shooting",
      "Strength"
    ], commander: true, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound."
    ] },
  { key: "poxwalker", name: "Poxwalker", points: 3, maxNumber: "-", profile: { move: "4\"", ws: 5, bs: 6, strength: 3, toughness: 3, wounds: 1, attacks: 2, ld: 4, save: 7 }, keywords: "Death Guard, Chaos, Nurgle, Heretic Astartes, Infantry, Poxwalker", wargear: "Improvised Weapon", specialisms: [
      "Combat",
      "Zealot"
    ], commander: false, abilities: [
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound."
    ] },
  { key: "tallyman", name: "Tallyman", points: 45, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 5, wounds: 4, attacks: 3, ld: 8, save: 3 }, keywords: "Death Guard, Chaos, Nurgle, Heretic Astartes, Infantry, Tallyman", wargear: "", specialisms: [
      "Fortitude",
      "Leadership",
      "Logistics",
      "Melee",
      "Shooting",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Disgustingly Resilient: Each time a model with this ability loses a wound, roll a D6; on a 5+ the model does not lose that wound.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] }
];

const FACTION = "Death Guard";

export const DEATH_GUARD_ITEMS = DEATH_GUARD_WEAPONS.map(w => ({ ...w, itemType: "weapon", faction: FACTION }));

export const DEATH_GUARD_MODEL_ITEMS = DEATH_GUARD_MODELS.map(m => ({ ...m, itemType: "model", faction: FACTION, rules: [] }));
