/**
 * Drukhari.
 *
 * Generated by tools/import_catalogue.py from the New Recruit catalogue,
 * which tracks Kill Team 2018 including errata and the Elites and Commanders
 * expansions. Do not hand-edit: re-run the importer instead.
 *
 * 18 models, 32 weapons.
 *
 * Ability text is imported as prose. Machine-readable rules are tagged
 * separately, by hand, in module/rules/ - deciding what an ability does is a
 * judgement call and is not safe to automate.
 */

export const DRUKHARI_WEAPONS = [
  { key: "baleblast", name: "Baleblast", points: 0, range: "18\"", weaponType: "assault", attacks: "2", strength: "4", ap: -1, damage: "1", abilities: "Each time you make a wound roll of 6+ for this weapon, the target suffers a mortal wound in addition to any other damage." },
  { key: "blast-pistol", name: "Blast pistol", points: 2, range: "6\"", weaponType: "pistol", attacks: "1", strength: "8", ap: -4, damage: "D6", abilities: "" },
  { key: "blaster", name: "Blaster", points: 3, range: "18\"", weaponType: "assault", attacks: "1", strength: "8", ap: -4, damage: "D6", abilities: "" },
  { key: "dark-lance", name: "Dark lance", points: 4, range: "36\"", weaponType: "heavy", attacks: "1", strength: "8", ap: -4, damage: "D6", abilities: "" },
  { key: "hexrifle", name: "Hexrifle", points: 1, range: "36\"", weaponType: "heavy", attacks: "1", strength: "4", ap: -1, damage: "1", abilities: "A model firing a hexrifle does not suffer the penalty to hit rolls for the target being at long range. Each time you roll a wound roll of 6+ for this weapon, it inflicts a mortal wound in addition to any other damage." },
  { key: "liquifier-gun", name: "Liquifier gun", points: 4, range: "8\"", weaponType: "assault", attacks: "D6", strength: "3", ap: 3, damage: "1", abilities: "Each time this weapon is fired, roll a D3 to determine its AP for those attacks. For example, if you rolled a 1, this weapon would have an AP of -1. This weapon automatically hits its target." },
  { key: "ossefactor", name: "Ossefactor", points: 5, range: "24\"", weaponType: "assault", attacks: "1", strength: "*", ap: -3, damage: "1", abilities: "This weapon always wounds on a roll of 2+. If a model is taken out of action by an attack made by this weapon, roll a D6 for each model within 2\" of that model. On a roll of 5+, that model suffers a mortal wound." },
  { key: "phantasm-grenade-launcher", name: "Phantasm grenade launcher", points: 1, range: "18\"", weaponType: "assault", attacks: "D3", strength: "1", ap: 0, damage: "1", abilities: "If a model is hit by one or more phantasm grenade launchers, subtract 1 from its Leadership characteristic until the end of the battle round." },
  { key: "plasma-grenade", name: "Plasma grenade", points: 0, range: "6\"", weaponType: "grenade", attacks: "D6", strength: "4", ap: -1, damage: "1", abilities: "" },
  { key: "shredder", name: "Shredder", points: 1, range: "12\"", weaponType: "assault", attacks: "D6", strength: "6", ap: -1, damage: "1", abilities: "When attacking an Infantry model, re-roll failed wound rolls for this weapon." },
  { key: "splinter-cannon", name: "Splinter cannon", points: 3, range: "36\"", weaponType: "rapidFire", attacks: "3", strength: "*", ap: 0, damage: "1", abilities: "This weapon wounds on a 4+." },
  { key: "splinter-pistol", name: "Splinter pistol", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "*", ap: 0, damage: "1", abilities: "This weapon wounds on a 4+." },
  { key: "splinter-rifle", name: "Splinter rifle", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "1", strength: "*", ap: 0, damage: "1", abilities: "This weapon wounds on a 4+." },
  { key: "stinger-pistol", name: "Stinger pistol", points: 1, range: "12\"", weaponType: "pistol", attacks: "1", strength: "*", ap: 0, damage: "1", abilities: "The weapon always wounds on a roll of 2+." },
  { key: "agonizer", name: "Agonizer", points: 2, range: "Melee", weaponType: "melee", attacks: "1", strength: "*", ap: -2, damage: "1", abilities: "This weapon always wounds on a 4+." },
  { key: "archite-glaive", name: "Archite glaive", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -3, damage: "1", abilities: "When attacking with this weapon, you must subtract 1 from the hit roll." },
  { key: "electrocorrosive-whip", name: "Electrocorrosive whip", points: 3, range: "Melee", weaponType: "melee", attacks: "1", strength: "*", ap: -2, damage: "2", abilities: "This weapon always wounds on a 4+." },
  { key: "flesh-gauntlet", name: "Flesh gauntlet", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "Each time you roll a wound roll of 6+ for this weapon , the target suffers a mortal wound in addition to any other damage." },
  { key: "glimmersteel-blade", name: "Glimmersteel blade", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "1", abilities: "" },
  { key: "haemonculus-tools", name: "Haemonculus tools", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "*", ap: 0, damage: "1", abilities: "This weapon always wounds on a roll of 4+." },
  { key: "hekatarii-blade", name: "Hekatarii blade", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "Each time the bearer fights, it can make 1 additional attack with this weapon." },
  { key: "huskblade", name: "Huskblade", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+1", ap: -2, damage: "D3", abilities: "" },
  { key: "hydra-gauntlets", name: "Hydra gauntlets", points: 2, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "1", abilities: "Each time the bearer fights, it can make 1 additional attack with this weapon. You can re-roll failed wound rolls for this weapon." },
  { key: "ichor-injector", name: "Ichor injector", points: 5, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "1", abilities: "The bearer can only make a single attack with this weapon each time it fights. You can re-roll failed wound rolls for this weapon. Each time you roll a wound roll of 6+ for this weapon, the target suffers D3 mortal wounds in addition to any other damage." },
  { key: "klaive", name: "Klaive", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+1", ap: -3, damage: "1", abilities: "" },
  { key: "mindphase-gauntlet", name: "Mindphase gauntlet", points: 1, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "2", abilities: "" },
  { key: "monstrous-cleaver", name: "Monstrous cleaver", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -2, damage: "1", abilities: "Each time the bearer fights, it can make 1 additional attack with this weapon." },
  { key: "power-sword", name: "Power sword", points: 2, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -3, damage: "1", abilities: "" },
  { key: "razorflails", name: "Razorflails", points: 2, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "1", abilities: "Each time the bearer fights, it can make 1 additional attack with this weapon. You can re-roll failed hit rolls for this weapon." },
  { key: "scissorhand", name: "Scissorhand", points: 2, range: "Melee", weaponType: "melee", attacks: "1", strength: "*", ap: -1, damage: "1", abilities: "Each time the bearer fights, it can make 1 additional attack with this weapon. This weapon always wounds on a roll of 4+." },
  { key: "shardnet-and-impaler", name: "Shardnet and Impaler", points: 2, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "2", abilities: "Each time the bearer fights, it can make 1 additional attack with this weapon." },
  { key: "venom-blade", name: "Venom blade", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "*", ap: 0, damage: "1", abilities: "This weapon always wounds on a roll of 2+." }
];

export const DRUKHARI_MODELS = [
  { key: "acothyst", name: "Acothyst", points: 9, maxNumber: "1", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 4, wounds: 1, attacks: 3, ld: 8, save: 6 }, keywords: "Drukhari, Aeldari, Haemonculus Coven, Infantry, Wrack", wargear: "Electrocorrosive whip; Hexrifle; Mindphase gauntlet; Scissorhand", specialisms: [
      "Combat",
      "Demolitions",
      "Medic",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Insensible to Pain: This model has a 5+ invulnerable save."
    ] },
  { key: "archon", name: "Archon", points: 56, maxNumber: "1", profile: { move: "8\"", ws: 2, bs: 2, strength: 3, toughness: 3, wounds: 5, attacks: 5, ld: 9, save: 5 }, keywords: "Drukhari, Aeldari, Archon, Commander, Infantry, Kabal", wargear: "", specialisms: [], commander: true, abilities: [] },
  { key: "grotesque", name: "Grotesque", points: 38, maxNumber: "-", profile: { move: "7\"", ws: 3, bs: 6, strength: 5, toughness: 5, wounds: 4, attacks: 4, ld: 8, save: 6 }, keywords: "Drukhari, Aeldari, Haemonculus Coven, Infantry, Grotesque", wargear: "Monstrous cleaver", specialisms: [
      "Combat",
      "Demolitions",
      "Zealot"
    ], commander: false, abilities: [
      "Insensible to Pain: This model has a 5+ invulnerable save."
    ] },
  { key: "haemonculus", name: "Haemonculus", points: 30, maxNumber: "1", profile: { move: "7\"", ws: 2, bs: 2, strength: 3, toughness: 4, wounds: 5, attacks: 5, ld: 8, save: 6 }, keywords: "Drukhari, Aeldari, Commander, Haemonculus, Infantry, Haemonculus Coven", wargear: "Ichor injector", specialisms: [
      "Ferocity",
      "Fortitude",
      "Logistics",
      "Melee",
      "Strength"
    ], commander: true, abilities: [] },
  { key: "hekatrix", name: "Hekatrix", points: 9, maxNumber: "1", profile: { move: "8\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 3, ld: 8, save: 6 }, keywords: "Drukhari, Aeldari, Infantry, Wych, Wych Cult", wargear: "", specialisms: [
      "Combat",
      "Scout",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Dodge: This model has a 4+ invulnerable save in the Fight phase.",
      "No Escape: Roll off if an INFANTRY model within 1\" of any enemy models with this ability would Fall Back. The model that would Fall Back can only do so if the player controlling it wins the roll-off."
    ] },
  { key: "incubus", name: "Incubus", points: 13, maxNumber: "-", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 3, ld: 8, save: 3 }, keywords: "Drukhari, Aeldari, Infantry, Incubus", wargear: "", specialisms: [
      "Combat",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [] },
  { key: "kabalite-gunner", name: "Kabalite Gunner", points: 8, maxNumber: "2", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 1, ld: 7, save: 5 }, keywords: "Drukhari, Aeldari, Infantry, Kabalite Warrior, Kabal", wargear: "", specialisms: [], commander: false, abilities: [] },
  { key: "kabalite-warrior", name: "Kabalite Warrior", points: 7, maxNumber: "-", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 1, ld: 7, save: 5 }, keywords: "Drukhari, Aeldari, Infantry, Kabalite Warrior, Kabal", wargear: "", specialisms: [
      "Comms",
      "Scout",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [] },
  { key: "klaivex", name: "Klaivex", points: 16, maxNumber: "1", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 2, attacks: 4, ld: 9, save: 3 }, keywords: "Drukhari, Aeldari, Infantry, Incubus", wargear: "", specialisms: [
      "Combat",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [] },
  { key: "mandrake", name: "Mandrake", points: 12, maxNumber: "-", profile: { move: "8\"", ws: 3, bs: 3, strength: 4, toughness: 3, wounds: 1, attacks: 3, ld: 7, save: 7 }, keywords: "Drukhari, Aeldari, Infantry, Mandrake", wargear: "Baleblast; Glimmersteel blade", specialisms: [
      "Combat",
      "Scout",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Shrouded from Sight: Subtract 1 from hit rolls for attacks that target this model. In addition, this model has a 5+ invulnerable save."
    ] },
  { key: "nightfiend", name: "Nightfiend", points: 13, maxNumber: "1", profile: { move: "8\"", ws: 3, bs: 3, strength: 4, toughness: 3, wounds: 1, attacks: 4, ld: 8, save: 7 }, keywords: "Drukhari, Aeldari, Infantry, Mandrake", wargear: "Baleblast; Glimmersteel blade", specialisms: [
      "Combat",
      "Scout",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Shrouded from Sight: Subtract 1 from hit rolls for attacks that target this model. In addition, this model has a 5+ invulnerable save."
    ] },
  { key: "succubus", name: "Succubus", points: 48, maxNumber: "1", profile: { move: "8\"", ws: 2, bs: 2, strength: 3, toughness: 3, wounds: 5, attacks: 4, ld: 8, save: 6 }, keywords: "Drukhari, Commander, Aeldari, Infantry, Succubus, Wych Cult", wargear: "", specialisms: [], commander: true, abilities: [] },
  { key: "sybarite", name: "Sybarite", points: 8, maxNumber: "1", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 2, ld: 8, save: 5 }, keywords: "Drukhari, Aeldari, Infantry, Kabalite Warrior, Kabal", wargear: "", specialisms: [
      "Comms",
      "Scout",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [] },
  { key: "vysa-kharavyxis", name: "Vysa Kharavyxis", points: 48, maxNumber: "1", profile: { move: "8\"", ws: 2, bs: 2, strength: 3, toughness: 3, wounds: 5, attacks: 4, ld: 8, save: 6 }, keywords: "Drukhari, Aeldari, Infantry, Wych Cult, Succubus, Level 1, Level 2, Level 3, Level 4", wargear: "Level 1 - Dancing with Death; Level 2 - Back from the Dead; Level 3 - Gladiatrix; Level 4 - Talent Scout", specialisms: [], commander: false, abilities: [] },
  { key: "wrack", name: "Wrack", points: 8, maxNumber: "-", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 4, wounds: 1, attacks: 2, ld: 7, save: 6 }, keywords: "Drukhari, Aeldari, Haemonculus Coven, Infantry, Wrack", wargear: "", specialisms: [], commander: false, abilities: [
      "Insensible to Pain: This model has a 5+ invulnerable save."
    ] },
  { key: "wrack-gunner", name: "Wrack Gunner", points: 9, maxNumber: "2", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 4, wounds: 1, attacks: 2, ld: 7, save: 6 }, keywords: "Drukhari, Aeldari, Haemonculus Coven, Infantry, Wrack", wargear: "Ossefactor", specialisms: [], commander: false, abilities: [
      "Insensible to Pain: This model has a 5+ invulnerable save."
    ] },
  { key: "wych", name: "Wych", points: 8, maxNumber: "-", profile: { move: "8\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 2, ld: 7, save: 6 }, keywords: "Drukhari, Aeldari, Infantry, Wych, Wych Cult", wargear: "", specialisms: [
      "Combat",
      "Scout",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Dodge: This model has a 4+ invulnerable save in the Fight phase.",
      "No Escape: Roll off if an INFANTRY model within 1\" of any enemy models with this ability would Fall Back. The model that would Fall Back can only do so if the player controlling it wins the roll-off."
    ] },
  { key: "wych-fighter", name: "Wych Fighter", points: 9, maxNumber: "3", profile: { move: "8\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 2, ld: 7, save: 6 }, keywords: "Drukhari, Aeldari, Infantry, Wych, Wych Cult", wargear: "Splinter Pistol and Hekatarii Blade", specialisms: [
      "Combat",
      "Scout",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Dodge: This model has a 4+ invulnerable save in the Fight phase.",
      "No Escape: Roll off if an INFANTRY model within 1\" of any enemy models with this ability would Fall Back. The model that would Fall Back can only do so if the player controlling it wins the roll-off."
    ] }
];

const FACTION = "Drukhari";

export const DRUKHARI_ITEMS = DRUKHARI_WEAPONS.map(w => ({ ...w, itemType: "weapon", faction: FACTION }));

export const DRUKHARI_MODEL_ITEMS = DRUKHARI_MODELS.map(m => ({ ...m, itemType: "model", faction: FACTION, rules: [] }));
