/**
 * Genestealer Cults.
 *
 * Generated by tools/import_catalogue.py from the New Recruit catalogue,
 * which tracks Kill Team 2018 including errata and the Elites and Commanders
 * expansions. Do not hand-edit: re-run the importer instead.
 *
 * 23 models, 46 weapons.
 *
 * Ability text is imported as prose. Machine-readable rules are tagged
 * separately, by hand, in module/rules/ - deciding what an ability does is a
 * judgement call and is not safe to automate.
 */

export const GENESTEALER_CULTS_WEAPONS = [
  { key: "autogun", name: "Autogun", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "1", strength: "3", ap: 0, damage: "1", abilities: "" },
  { key: "autopistol", name: "Autopistol", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "3", ap: 0, damage: "1", abilities: "" },
  { key: "blasting-charge", name: "Blasting Charge", points: 0, range: "6\"", weaponType: "grenade", attacks: "D6", strength: "3", ap: 0, damage: "1", abilities: "" },
  { key: "bolt-pistol", name: "Bolt Pistol", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "demolition-charge", name: "Demolition Charge", points: 3, range: "6\"", weaponType: "grenade", attacks: "D6", strength: "8", ap: -3, damage: "D3", abilities: "Each demolition charge can only be used once per battle." },
  { key: "flamer", name: "Flamer", points: 3, range: "8\"", weaponType: "assault", attacks: "D6", strength: "4", ap: 0, damage: "1", abilities: "This weapon automatically hits its target." },
  { key: "flesh-hooks", name: "Flesh Hooks", points: 0, range: "6\"", weaponType: "assault", attacks: "2", strength: "User", ap: 0, damage: "1", abilities: "The weapon can be fired within 1\" of an enemy model, and can target enemy models within 1\" of friendly models." },
  { key: "grenade-launcher-frag", name: "Grenade Launcher (Frag)", points: 0, range: "24\"", weaponType: "assault", attacks: "D6", strength: "3", ap: 0, damage: "1", abilities: "" },
  { key: "grenade-launcher-krak", name: "Grenade Launcher (Krak)", points: 0, range: "24\"", weaponType: "assault", attacks: "1", strength: "6", ap: -1, damage: "D3", abilities: "" },
  { key: "hand-flamer", name: "Hand Flamer", points: 2, range: "6\"", weaponType: "pistol", attacks: "D3", strength: "3", ap: 0, damage: "1", abilities: "This weapon automatically hits its target." },
  { key: "heavy-stubber", name: "Heavy Stubber", points: 0, range: "36\"", weaponType: "heavy", attacks: "3", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "liberator-autostub", name: "Liberator autostub", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "4", ap: -1, damage: "2", abilities: "" },
  { key: "mining-laser", name: "Mining Laser", points: 3, range: "24\"", weaponType: "heavy", attacks: "1", strength: "9", ap: -3, damage: "D6", abilities: "" },
  { key: "needle-pistol", name: "Needle Pistol", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "1", ap: 0, damage: "1", abilities: "This weapon always wounds on a roll of 2+." },
  { key: "seismic-cannon-long-wave", name: "Seismic Cannon (Long-wave)", points: 0, range: "24\"", weaponType: "heavy", attacks: "4", strength: "3", ap: 0, damage: "1", abilities: "All wound rolls of 6+ have an AP of -4." },
  { key: "seismic-cannon-short-wave", name: "Seismic Cannon (Short-wave)", points: 0, range: "12\"", weaponType: "heavy", attacks: "2", strength: "6", ap: -1, damage: "2", abilities: "All wound rolls of 6+ have an AP of -4." },
  { key: "shotgun", name: "Shotgun", points: 0, range: "12\"", weaponType: "assault", attacks: "2", strength: "3", ap: 0, damage: "1", abilities: "If the target is within half range, add 1 to the weapon's Strength." },
  { key: "silencer-sniper-rifle", name: "Silencer sniper rifle", points: 0, range: "36\"", weaponType: "heavy", attacks: "1", strength: "4", ap: -1, damage: "D3", abilities: "A model firing this weapon does not suffer the penalty to its hit rolls for the target being at long range. If you roll a wound roll of 6+ for this weapon, it inflicts a mortal wound in addition to its normal damage. If a PSYKER loses any wounds as a result of this weapon's attacks, after all of this weapon's attacks have been resolved that model suffers Perils of the Warp." },
  { key: "web-pistol", name: "Web Pistol", points: 0, range: "12\"", weaponType: "pistol", attacks: "D3", strength: "3", ap: 0, damage: "1", abilities: "When making a shooting attack with a web weapon, you can either use the Strength or Toughness characteristic of the target to determine the wound roll - whichever is lowest." },
  { key: "webber", name: "Webber", points: 1, range: "16\"", weaponType: "assault", attacks: "D3", strength: "4", ap: 0, damage: "1", abilities: "When making a shooting attack with a web weapon, you can either use the Strength or Toughness characteristic of the target to determine the wound roll - whichever is lowest." },
  { key: "acid-maw", name: "Acid Maw", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -3, damage: "1", abilities: "" },
  { key: "bonesword", name: "Bonesword", points: 1, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -2, damage: "1", abilities: "" },
  { key: "chainsword", name: "Chainsword", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "Each time the bearer fights, it can make 1 additional attack with this weapon." },
  { key: "cultist-knife", name: "Cultist Knife", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "Each time the bearer fights, it can make 1 additional attack with this weapon." },
  { key: "cultist-knife", name: "Cultist knife", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "Each time the bearer fights, it can make 1 additional attack with this weapon." },
  { key: "familiar-claws", name: "Familiar claws", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "4", ap: 0, damage: "1", abilities: "When this model fights, you can choose to use this weapon. After this model fights, you can make two additional attacks using this weapon." },
  { key: "force-stave", name: "Force Stave", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -1, damage: "D3", abilities: "" },
  { key: "heavy-rock-cutter", name: "Heavy Rock Cutter", points: 4, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -4, damage: "2", abilities: "Roll a D6 each time a model suffers damage from this weapon; if you roll higher than the model's remaining number of Wounds, it is instantly taken out of action. When attacking with this weapon, you must subtract 1 from the hit roll." },
  { key: "heavy-rock-drill", name: "Heavy Rock Drill", points: 5, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -3, damage: "1", abilities: "Roll a D6 each time a model suffers damage from this weapon; on a 2+ the model suffers a mortal wound and roll another D6. This time, the model suffers a mortal wound on a 3+. Keep rolling a D6, increasing the score required to cause a mortal wound by 1 each time, until the model's wounds are reduced to 0 or the roll is failed." },
  { key: "heavy-rock-saw", name: "Heavy Rock Saw", points: 4, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -4, damage: "2", abilities: "" },
  { key: "hypermorph-tail", name: "Hypermorph tail", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "1", abilities: "Each time the bearer fights, it can make 1 additional attack with this weapon." },
  { key: "injector-goad", name: "Injector goad", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+1", ap: 0, damage: "D3", abilities: "This weapon always wounds on a 2+. If a COMMANDER loses any wounds from this weapon, roll a D6 for it after all of this model's attacks have been resolved. If the result is higher than the Wounds characteristic of the COMMANDER, it suffers D3 mortal wounds." },
  { key: "lash-whip-and-bonesword", name: "Lash Whip and Bonesword", points: 2, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -2, damage: "1", abilities: "If the bearer is taken out of action in the Fight phase before it has made its attacks in that phase, it may immediately fight before being removed from the battlefield." },
  { key: "locus-blades", name: "Locus blades", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -3, damage: "1", abilities: "This weapon's Damage characteristic is 2 in a battle round in which this model charged, was charged or performed a Sudden Strike." },
  { key: "metamorph-claw", name: "Metamorph Claw", points: 1, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: 0, damage: "1", abilities: "" },
  { key: "metamorph-talon", name: "Metamorph Talon", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "Add 1 to hit rolls for this weapon." },
  { key: "metamorph-whip", name: "Metamorph Whip", points: 1, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "If the bearer is taken out of action in the Fight phase before it has made its attacks in that phase, it may immediately fight before being removed from the battlefield." },
  { key: "monstrous-rending-claws", name: "Monstrous Rending Claws", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -3, damage: "D3", abilities: "You can re-roll failed wound rolls for this weapon. In addition, each time you make a wound roll of 6+, that hit is resolved with an AP of -6 and Damage of 3." },
  { key: "power-hammer", name: "Power Hammer", points: 4, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -3, damage: "3", abilities: "When attacking with this weapon, you must subtract 1 from the hit rolls." },
  { key: "power-maul", name: "Power Maul", points: 1, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -1, damage: "1", abilities: "" },
  { key: "power-pick", name: "Power Pick", points: 3, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -2, damage: "D3", abilities: "" },
  { key: "rending-claw", name: "Rending Claw", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "1", abilities: "Each time you make a wound roll of 6+ for this weapon, that hit is resolved with an AP of -4." },
  { key: "rending-claws", name: "Rending Claws", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "1", abilities: "Each time you make a wound roll of 6+ for this weapon, that hit is resolved with an AP of -4." },
  { key: "sanctus-bio-dagger", name: "Sanctus bio-dagger", points: 20, range: "Melee", weaponType: "melee", attacks: "1", strength: "1", ap: -2, damage: "2", abilities: "Each time the bearer fights, it can make 1 additional attack with this weapon. In addition, this weapon wounds on a 2+." },
  { key: "scything-talons", name: "Scything Talons", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "You can re-roll hit rolls of 1 for this weapon. If the bearer has more than one pair of scything talons, it can made 1 additional attack with them each time it fights." },
  { key: "toxin-injector-claw", name: "Toxin Injector Claw", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "1", abilities: "This weapon always wounds on a roll of 2+. Furthermore, each time you make a wound roll of 6+ with this weapon, that hit is resolved with an AP of -4." }
];

export const GENESTEALER_CULTS_MODELS = [
  { key: "aberrant", name: "Aberrant", points: 15, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 6, strength: 5, toughness: 4, wounds: 2, attacks: 2, ld: 7, save: 5 }, keywords: "Genestealer Cults, Tyranids, Infantry", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Zealot"
    ], commander: false, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\"."
    ] },
  { key: "acolyte-fighter", name: "Acolyte Fighter", points: 8, maxNumber: "4", profile: { move: "6\"", ws: 3, bs: 4, strength: 4, toughness: 3, wounds: 1, attacks: 2, ld: 7, save: 5 }, keywords: "Genestealer Cults, Tyranids, Infantry", wargear: "Cultist Knife and Rending Claw", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Zealot"
    ], commander: false, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\"."
    ] },
  { key: "acolyte-hybrid", name: "Acolyte Hybrid", points: 7, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 4, strength: 4, toughness: 3, wounds: 1, attacks: 2, ld: 7, save: 5 }, keywords: "Genestealer Cults, Tyranids, Infantry", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Zealot"
    ], commander: false, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\"."
    ] },
  { key: "acolyte-iconward", name: "Acolyte Iconward", points: 18, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 3, wounds: 4, attacks: 4, ld: 8, save: 5 }, keywords: "Genestealer Cults, Tyranids, Infantry, Commander, Acolyte Iconward", wargear: "", specialisms: [
      "Ferocity",
      "Fortitude",
      "Leadership",
      "Melee",
      "Stealth"
    ], commander: true, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\".",
      "Unquestioning Loyalty: Roll a D6 each time you use the Look Out, Sir! Commander Tactic on this model. On a 2+, you gain a Command Point."
    ] },
  { key: "acolyte-leader", name: "Acolyte Leader", points: 8, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 4, strength: 4, toughness: 3, wounds: 1, attacks: 3, ld: 8, save: 5 }, keywords: "Genestealer Cults, Tyranids, Infantry", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Zealot"
    ], commander: false, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\"."
    ] },
  { key: "alchemicus-familiar", name: "Alchemicus Familiar", points: 4, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 6, strength: 4, toughness: 3, wounds: 1, attacks: 2, ld: 8, save: 6 }, keywords: "Genestealer Cults, Infantry, Familiar", wargear: "", specialisms: [], commander: false, abilities: [] },
  { key: "biophagus", name: "Biophagus", points: 29, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 4, attacks: 3, ld: 8, save: 5 }, keywords: "Genestealer Cults, Infantry, Biophagus", wargear: "Injector goad", specialisms: [
      "Logistics",
      "Strategist"
    ], commander: true, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\".",
      "Unquestioning Loyalty: Roll a D6 each time you use the Look Out, Sir! Commander Tactic on this model. On a 2+, you gain a Command Point."
    ] },
  { key: "clamavus", name: "Clamavus", points: 26, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 4, attacks: 3, ld: 8, save: 5 }, keywords: "Genestealer Cults, Infantry, Clamavus", wargear: "", specialisms: [
      "Leadership",
      "Strategist"
    ], commander: true, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\".",
      "Unquestioning Loyalty: Roll a D6 each time you use the Look Out, Sir! Commander Tactic on this model. On a 2+, you gain a Command Point."
    ] },
  { key: "crasker-matterzhek", name: "Crasker Matterzhek", points: 18, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 3, wounds: 5, attacks: 4, ld: 8, save: 5 }, keywords: "Genestealer Cults, Tyranids, Infantry, Commander, Acolyte Iconward, Level 1, Level 2, Level 3, Level 4", wargear: "Level 1: Sacred Duty; Level 2: Fearless Dedication; Level 3: Scale the Heights; Level 4: Raise the Standard High; Sacred Duty", specialisms: [], commander: true, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\".",
      "Unquestioning Loyalty: Roll a D6 each time you use the Look Out, Sir! Commander Tactic on this model. On a 2+, you gain a Command Point."
    ] },
  { key: "genestealer", name: "Genestealer", points: 11, maxNumber: "-", profile: { move: "8\"", ws: 3, bs: 4, strength: 4, toughness: 4, wounds: 1, attacks: 3, ld: 9, save: 5 }, keywords: "Genestealer Cults, Infantry", wargear: "Extended Carapace; Flesh Hooks", specialisms: [
      "Combat",
      "Scout",
      "Veteran"
    ], commander: false, abilities: [] },
  { key: "ghyrson-stark", name: "Ghyrson Stark", points: 25, maxNumber: "1", profile: { move: "7\"", ws: 3, bs: 2, strength: 3, toughness: 3, wounds: 4, attacks: 3, ld: 8, save: 5 }, keywords: "Genestealer Cults, Tyranids, Infantry, Kelermorph, Level 1, Level 2, Level 3, Level 4", wargear: "Cultist knife; Level 1 - Hybrid Agility; Level 2 - Preternatural Skill; Level 3 - Swift Reflexes; Level 4 - Trick Shooter; Liberator autostub", specialisms: [], commander: false, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\"."
    ] },
  { key: "hybrid-metamorph", name: "Hybrid Metamorph", points: 8, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 4, strength: 4, toughness: 3, wounds: 1, attacks: 3, ld: 7, save: 5 }, keywords: "Genestealer Cults, Tyranids, Infantry", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Zealot"
    ], commander: false, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\"."
    ] },
  { key: "kelermorph", name: "Kelermorph", points: 25, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 2, strength: 3, toughness: 3, wounds: 4, attacks: 3, ld: 8, save: 5 }, keywords: "Genestealer Cults, Tyranids, Infantry, Kelermorph", wargear: "Cultist knife; Liberator autostub", specialisms: [
      "Fortitude",
      "Leadership",
      "Shooting",
      "Stealth"
    ], commander: true, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\"."
    ] },
  { key: "locus", name: "Locus", points: 66, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 3, wounds: 4, attacks: 4, ld: 8, save: 5 }, keywords: "Genestealer Cults, Infantry, Locus", wargear: "Hypermorph tail; Locus blades", specialisms: [
      "Ferocity",
      "Melee",
      "Stealth"
    ], commander: true, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\"."
    ] },
  { key: "magus", name: "Magus", points: 30, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 4, attacks: 3, ld: 8, save: 5 }, keywords: "Genestealer Cults, Tyranids, Infantry, Commander, Psyker, Magus", wargear: "Force Stave", specialisms: [
      "Leadership",
      "Logistics",
      "Psyker",
      "Stealth"
    ], commander: true, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\".",
      "Unquestioning Loyalty: Roll a D6 each time you use the Look Out, Sir! Commander Tactic on this model. On a 2+, you gain a Command Point."
    ] },
  { key: "metamorph-leader", name: "Metamorph Leader", points: 9, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 4, strength: 4, toughness: 3, wounds: 1, attacks: 4, ld: 8, save: 5 }, keywords: "Genestealer Cults, Tyranids, Infantry", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Zealot"
    ], commander: false, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\"."
    ] },
  { key: "neophyte-gunner", name: "Neophyte Gunner", points: 6, maxNumber: "4", profile: { move: "6\"", ws: 4, bs: 4, strength: 3, toughness: 3, wounds: 1, attacks: 1, ld: 7, save: 5 }, keywords: "Genestealer Cults, Tyranids, Infantry", wargear: "", specialisms: [
      "Demolitions",
      "Heavy",
      "Medic",
      "Scout",
      "Zealot"
    ], commander: false, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\"."
    ] },
  { key: "neophyte-hybrid", name: "Neophyte Hybrid", points: 5, maxNumber: "-", profile: { move: "6\"", ws: 4, bs: 4, strength: 3, toughness: 3, wounds: 1, attacks: 1, ld: 7, save: 5 }, keywords: "Genestealer Cults, Tyranids, Infantry", wargear: "", specialisms: [
      "Demolitions",
      "Medic",
      "Scout",
      "Zealot"
    ], commander: false, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\"."
    ] },
  { key: "neophyte-leader", name: "Neophyte Leader", points: 6, maxNumber: "1", profile: { move: "6\"", ws: 4, bs: 4, strength: 3, toughness: 3, wounds: 1, attacks: 2, ld: 8, save: 5 }, keywords: "Genestealer Cults, Tyranids, Infantry", wargear: "", specialisms: [
      "Demolitions",
      "Medic",
      "Scout",
      "Zealot"
    ], commander: false, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\"."
    ] },
  { key: "nexos", name: "Nexos", points: 32, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 4, attacks: 3, ld: 8, save: 5 }, keywords: "Genestealer Cults, Infantry, Nexus", wargear: "", specialisms: [
      "Logistics",
      "Strategist"
    ], commander: true, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\".",
      "Unquestioning Loyalty: Roll a D6 each time you use the Look Out, Sir! Commander Tactic on this model. On a 2+, you gain a Command Point."
    ] },
  { key: "patriarch", name: "Patriarch", points: 131, maxNumber: "1", profile: { move: "8\"", ws: 2, bs: 5, strength: 6, toughness: 5, wounds: 6, attacks: 6, ld: 10, save: 4 }, keywords: "Genestealer Cults, Infantry, Commander, Psyker, Patriarch, Tyranids", wargear: "Monstrous Rending Claws; The Horror", specialisms: [
      "Ferocity",
      "Fortitude",
      "Melee",
      "Psyker",
      "Stealth",
      "Strength"
    ], commander: true, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\".",
      "Unquestioning Loyalty: Roll a D6 each time you use the Look Out, Sir! Commander Tactic on this model. On a 2+, you gain a Command Point."
    ] },
  { key: "primus", name: "Primus", points: 28, maxNumber: "1", profile: { move: "6\"", ws: 2, bs: 3, strength: 4, toughness: 3, wounds: 5, attacks: 4, ld: 9, save: 5 }, keywords: "Genestealer Cults, Tyranids, Infantry, Commander, Primus", wargear: "Needle Pistol; Toxin Injector Claw", specialisms: [
      "Ferocity",
      "Fortitude",
      "Leadership",
      "Logistics",
      "Melee",
      "Shooting",
      "Stealth",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\".",
      "Unquestioning Loyalty: Roll a D6 each time you use the Look Out, Sir! Commander Tactic on this model. On a 2+, you gain a Command Point."
    ] },
  { key: "sanctus", name: "Sanctus", points: 33, maxNumber: "1", profile: { move: "6\"", ws: 2, bs: 2, strength: 3, toughness: 3, wounds: 4, attacks: 4, ld: 8, save: 5 }, keywords: "Genestealer Cults, Infantry, Sanctus", wargear: "Familiar claws; Sanctus bio-dagger; Silencer sniper rifle", specialisms: [
      "Melee",
      "Shooting",
      "Stealth"
    ], commander: true, abilities: [
      "Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6\"."
    ] }
];

const FACTION = "Genestealer Cults";

export const GENESTEALER_CULTS_ITEMS = GENESTEALER_CULTS_WEAPONS.map(w => ({ ...w, itemType: "weapon", faction: FACTION }));

export const GENESTEALER_CULTS_MODEL_ITEMS = GENESTEALER_CULTS_MODELS.map(m => ({ ...m, itemType: "model", faction: FACTION, rules: [] }));
