/**
 * Grey Knights.
 *
 * Generated by tools/import_catalogue.py from the New Recruit catalogue,
 * which tracks Kill Team 2018 including errata and the Elites and Commanders
 * expansions. Do not hand-edit: re-run the importer instead.
 *
 * 12 models, 17 weapons.
 *
 * Ability text is imported as prose. Machine-readable rules are tagged
 * separately, by hand, in module/rules/ - deciding what an ability does is a
 * judgement call and is not safe to automate.
 */

export const GREY_KNIGHTS_WEAPONS = [
  { key: "boltgun", name: "Boltgun", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "1", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "flamer", name: "Flamer", points: 0, range: "8\"", weaponType: "assault", attacks: "D6", strength: "4", ap: 0, damage: "1", abilities: "This weapon automatically hits its target." },
  { key: "frag-grenade", name: "Frag grenade", points: 0, range: "6\"", weaponType: "grenade", attacks: "D6", strength: "3", ap: 0, damage: "1", abilities: "" },
  { key: "incinerator", name: "Incinerator", points: 3, range: "8\"", weaponType: "assault", attacks: "D6", strength: "6", ap: -1, damage: "1", abilities: "This weapon automatically hits its targets." },
  { key: "krak-grenade", name: "Krak Grenade", points: 0, range: "6\"", weaponType: "grenade", attacks: "1", strength: "6", ap: -1, damage: "D3", abilities: "" },
  { key: "meltagun", name: "Meltagun", points: 0, range: "12\"", weaponType: "assault", attacks: "1", strength: "8", ap: -4, damage: "D6", abilities: "If target is within half range of this weapon, roll two dice when inflicting damage with it and discard the lowest result." },
  { key: "plasma-gun-standard", name: "Plasma gun - standard", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "1", strength: "7", ap: -3, damage: "1", abilities: "" },
  { key: "plasma-gun-supercharge", name: "Plasma gun - supercharge", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "1", strength: "8", ap: -3, damage: "2", abilities: "On an unmodified hit roll of 1, the bearer of this weapon is taken out of action after all this weapon's shots have been resolved." },
  { key: "psilencer", name: "Psilencer", points: 3, range: "24\"", weaponType: "heavy", attacks: "6", strength: "4", ap: 0, damage: "D3", abilities: "" },
  { key: "psycannon", name: "Psycannon", points: 2, range: "24\"", weaponType: "heavy", attacks: "4", strength: "7", ap: -1, damage: "1", abilities: "" },
  { key: "psyk-out-grenade", name: "Psyk-out grenade", points: 0, range: "6\"", weaponType: "grenade", attacks: "D3", strength: "2", ap: 0, damage: "1", abilities: "Each time you roll a hit roll of 6+ for this weapon when targeting a PSYKER or DAEMON, the target suffers a mortal wound instead of the normal damage." },
  { key: "storm-bolter", name: "Storm bolter", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "2", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "nemesis-daemon-hammer", name: "Nemesis Daemon Hammer", points: 2, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -3, damage: "3", abilities: "When a model attacks with this weapon, you must subtract 1 from the hit roll." },
  { key: "nemesis-falchion", name: "Nemesis Falchion", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -2, damage: "D3", abilities: "If a model is armed with two Nemesis falchions, each time it fights it can make 1 additional attack with them." },
  { key: "nemesis-force-halberd", name: "Nemesis Force Halberd", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+1", ap: -2, damage: "D3", abilities: "" },
  { key: "nemesis-force-sword", name: "Nemesis Force Sword", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -3, damage: "D3", abilities: "" },
  { key: "nemesis-warding-stave", name: "Nemesis Warding Stave", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -1, damage: "D3", abilities: "A model armed with this weapon has a 5+ invulnerable save against attacks made in the Fight phase. If it already has an invulnerable save, add 1 to invulnerable saving throws you make for it in the Fight phase instead." }
];

export const GREY_KNIGHTS_MODELS = [
  { key: "brother-captain", name: "Brother-Captain", points: 100, maxNumber: "1", profile: { move: "5\"", ws: 2, bs: 2, strength: 4, toughness: 4, wounds: 6, attacks: 4, ld: 9, save: 2 }, keywords: "Grey Knights, Imperium, Adeptus Astartes, Infantry, Terminator, Brother-captain, Psyker", wargear: "Hammerhand", specialisms: [
      "Ferocity",
      "Fortitude",
      "Leadership",
      "Logistics",
      "Melee",
      "Psyker",
      "Shooting",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model\u2019s hit rolls from one flesh wound it has suffered.",
      "Daemon Hunters: If this model attacks any DAEMONS in the Fight phase, you can re-roll failed wound rolls for those attacks.",
      "Rites of Banishment: When the model manifests the Psybolt psychic power it has a range of 12\". If Psybolt is successfully manifested, and the target model is a DAEMON, the target suffers D3 mortal wounds even if the result of the Psychic test was not 11+."
    ] },
  { key: "brotherhood-champion", name: "Brotherhood Champion", points: 108, maxNumber: "1", profile: { move: "6\"", ws: 2, bs: 2, strength: 4, toughness: 4, wounds: 4, attacks: 4, ld: 8, save: 2 }, keywords: "Grey Knights, Imperium, Adeptus Astartes, Commander, Infantry, Psyker, Brotherhood Champion", wargear: "Hammerhand; Nemesis force sword; Storm bolter", specialisms: [
      "Fortitude",
      "Leadership",
      "Melee",
      "Psyker",
      "Shooting",
      "Strength"
    ], commander: true, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Daemon Hunters: If this model attacks any DAEMONS in the Fight phase, you can re-roll failed wound rolls for those attacks.",
      "Rites of Banishment: When the model manifests the Psybolt psychic power it has a range of 12\". If Psybolt is successfully manifested, and the target model is a DAEMON, the target suffers D3 mortal wounds even if the result of the Psychic test was not 11+."
    ] },
  { key: "grey-knight", name: "Grey Knight", points: 18, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 1, attacks: 1, ld: 7, save: 3 }, keywords: "Grey Knights, Imperium, Adeptus Astartes, Infantry, Psyker, Grey Knight", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Rites of Banishment: When the model manifests the Psybolt psychic power it has a range of 12\". If Psybolt is successfully manifested, and the target model is a DAEMON, the target suffers D3 mortal wounds even if the result of the Psychic test was not 11+.",
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model\u2019s hit rolls from one flesh wound it has suffered.",
      "Daemon Hunters: If this model attacks any DAEMONS in the Fight phase, you can re-roll failed wound rolls for those attacks."
    ] },
  { key: "grey-knight-gunner", name: "Grey Knight Gunner", points: 19, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 1, attacks: 1, ld: 7, save: 3 }, keywords: "Grey Knights, Imperium, Adeptus Astartes, Infantry, Psyker, Grey Knight", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Heavy",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Daemon Hunters: If this model attacks any DAEMONS in the Fight phase, you can re-roll failed wound rolls for those attacks.",
      "Rites of Banishment: When the model manifests the Psybolt psychic power it has a range of 12\". If Psybolt is successfully manifested, and the target model is a DAEMON, the target suffers D3 mortal wounds even if the result of the Psychic test was not 11+.",
      "Transhuman Physiology: Ignore the penalty to this model\u2019s hit rolls from one flesh wound it has suffered."
    ] },
  { key: "justicar", name: "Justicar", points: 19, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 1, attacks: 2, ld: 8, save: 3 }, keywords: "Grey Knights, Imperium, Adeptus Astartes, Infantry, Psyker, Grey Knight", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Daemon Hunters: If this model attacks any DAEMONS in the Fight phase, you can re-roll failed wound rolls for those attacks.",
      "Rites of Banishment: When the model manifests the Psybolt psychic power it has a range of 12\". If Psybolt is successfully manifested, and the target model is a DAEMON, the target suffers D3 mortal wounds even if the result of the Psychic test was not 11+.",
      "Transhuman Physiology: Ignore the penalty to this model\u2019s hit rolls from one flesh wound it has suffered."
    ] },
  { key: "librarian", name: "Librarian", points: 96, maxNumber: "1", profile: { move: "5\"", ws: 2, bs: 2, strength: 4, toughness: 4, wounds: 5, attacks: 3, ld: 9, save: 2 }, keywords: "Grey Knights, Imperium, Adeptus Astartes, Infantry, Terminator, Psyker, Librarian", wargear: "", specialisms: [
      "Fortitude",
      "Melee",
      "Psyker",
      "Shooting",
      "Strength"
    ], commander: true, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model\u2019s hit rolls from one flesh wound it has suffered.",
      "Rites of Banishment: When the model manifests the Psybolt psychic power it has a range of 12\". If Psybolt is successfully manifested, and the target model is a DAEMON, the target suffers D3 mortal wounds even if the result of the Psychic test was not 11+.",
      "Daemon Hunters: If this model attacks any DAEMONS in the Fight phase, you can re-roll failed wound rolls for those attacks."
    ] },
  { key: "paladin", name: "Paladin", points: 47, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 3, attacks: 3, ld: 8, save: 2 }, keywords: "Grey Knights, Imperium, Adeptus Astartes, Infantry, Psyker, Terminator, Paladin", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model\u2019s hit rolls from one flesh wound it has suffered.",
      "Rites of Banishment: When the model manifests the Psybolt psychic power it has a range of 12\". If Psybolt is successfully manifested, and the target model is a DAEMON, the target suffers D3 mortal wounds even if the result of the Psychic test was not 11+.",
      "Daemon Hunters: If this model attacks any DAEMONS in the Fight phase, you can re-roll failed wound rolls for those attacks."
    ] },
  { key: "paladin-gunner", name: "Paladin Gunner", points: 48, maxNumber: "2", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 3, attacks: 3, ld: 8, save: 2 }, keywords: "Grey Knights, Imperium, Adeptus Astartes, Infantry, Psyker, Terminator, Paladin", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Heavy",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model\u2019s hit rolls from one flesh wound it has suffered.",
      "Rites of Banishment: When the model manifests the Psybolt psychic power it has a range of 12\". If Psybolt is successfully manifested, and the target model is a DAEMON, the target suffers D3 mortal wounds even if the result of the Psychic test was not 11+.",
      "Daemon Hunters: If this model attacks any DAEMONS in the Fight phase, you can re-roll failed wound rolls for those attacks."
    ] },
  { key: "paragon", name: "Paragon", points: 50, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 3, attacks: 3, ld: 9, save: 2 }, keywords: "Grey Knights, Imperium, Adeptus Astartes, Infantry, Psyker, Terminator, Paladin", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model\u2019s hit rolls from one flesh wound it has suffered.",
      "Rites of Banishment: When the model manifests the Psybolt psychic power it has a range of 12\". If Psybolt is successfully manifested, and the target model is a DAEMON, the target suffers D3 mortal wounds even if the result of the Psychic test was not 11+.",
      "Daemon Hunters: If this model attacks any DAEMONS in the Fight phase, you can re-roll failed wound rolls for those attacks."
    ] },
  { key: "terminator", name: "Terminator", points: 36, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 7, save: 2 }, keywords: "Grey Knights, Imperium, Adeptus Astartes, Infantry, Psyker, Terminator", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model\u2019s hit rolls from one flesh wound it has suffered.",
      "Rites of Banishment: When the model manifests the Psybolt psychic power it has a range of 12\". If Psybolt is successfully manifested, and the target model is a DAEMON, the target suffers D3 mortal wounds even if the result of the Psychic test was not 11+.",
      "Daemon Hunters: If this model attacks any DAEMONS in the Fight phase, you can re-roll failed wound rolls for those attacks."
    ] },
  { key: "terminator-gunner", name: "Terminator Gunner", points: 37, maxNumber: "2", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 7, save: 2 }, keywords: "Grey Knights, Imperium, Adeptus Astartes, Infantry, Psyker, Terminator", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Heavy",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model\u2019s hit rolls from one flesh wound it has suffered.",
      "Rites of Banishment: When the model manifests the Psybolt psychic power it has a range of 12\". If Psybolt is successfully manifested, and the target model is a DAEMON, the target suffers D3 mortal wounds even if the result of the Psychic test was not 11+.",
      "Daemon Hunters: If this model attacks any DAEMONS in the Fight phase, you can re-roll failed wound rolls for those attacks."
    ] },
  { key: "terminator-justicar", name: "Terminator Justicar", points: 39, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 3, ld: 8, save: 2 }, keywords: "Grey Knights, Imperium, Adeptus Astartes, Infantry, Psyker, Terminator", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model\u2019s hit rolls from one flesh wound it has suffered.",
      "Rites of Banishment: When the model manifests the Psybolt psychic power it has a range of 12\". If Psybolt is successfully manifested, and the target model is a DAEMON, the target suffers D3 mortal wounds even if the result of the Psychic test was not 11+.",
      "Daemon Hunters: If this model attacks any DAEMONS in the Fight phase, you can re-roll failed wound rolls for those attacks."
    ] }
];

const FACTION = "Grey Knights";

export const GREY_KNIGHTS_ITEMS = GREY_KNIGHTS_WEAPONS.map(w => ({ ...w, itemType: "weapon", faction: FACTION }));

export const GREY_KNIGHTS_MODEL_ITEMS = GREY_KNIGHTS_MODELS.map(m => ({ ...m, itemType: "model", faction: FACTION, rules: [] }));
