/**
 * Harlequins.
 *
 * Generated by tools/import_catalogue.py from the New Recruit catalogue,
 * which tracks Kill Team 2018 including errata and the Elites and Commanders
 * expansions. Do not hand-edit: re-run the importer instead.
 *
 * 4 models, 13 weapons.
 *
 * Ability text is imported as prose. Machine-readable rules are tagged
 * separately, by hand, in module/rules/ - deciding what an ability does is a
 * judgement call and is not safe to automate.
 */

export const HARLEQUINS_WEAPONS = [
  { key: "fusion-pistol", name: "Fusion pistol", points: 3, range: "6\"", weaponType: "pistol", attacks: "1", strength: "8", ap: -4, damage: "D6", abilities: "" },
  { key: "hallucinogen-grenade-launcher", name: "Hallucinogen grenade launcher", points: 0, range: "18\"", weaponType: "assault", attacks: "1", strength: "*", ap: 0, damage: "*", abilities: "If a model is hit by this weapon, roll 2D6 - if the result is equal to or greater than the target model's Leadership, it suffers a mortal wound." },
  { key: "neuro-disruptor", name: "Neuro disruptor", points: 2, range: "12\"", weaponType: "pistol", attacks: "1", strength: "4", ap: -3, damage: "D3", abilities: "" },
  { key: "plasma-grenade", name: "Plasma grenade", points: 0, range: "6\"", weaponType: "grenade", attacks: "D6", strength: "4", ap: -1, damage: "1", abilities: "" },
  { key: "shrieker-cannon-shrieker", name: "Shrieker Cannon - Shrieker", points: 0, range: "24\"", weaponType: "assault", attacks: "1", strength: "6", ap: -1, damage: "1", abilities: "Each time an INFANTRY model is slain by an attack made with this weapon, roll a D6 for each enemy model within 2\" of that model. On a roll of 4+ the model being rolled for suffers a mortal wound." },
  { key: "shrieker-cannon-shuriken", name: "Shrieker Cannon - Shuriken", points: 0, range: "24\"", weaponType: "assault", attacks: "3", strength: "6", ap: 0, damage: "1", abilities: "" },
  { key: "shuriken-pistol", name: "Shuriken pistol", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "4", ap: 0, damage: "1", abilities: "Each time you make a wound roll of 6+ for this weapon, that hit is resolved with an AP of -3." },
  { key: "harlequin-s-blade", name: "Harlequin's blade", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "" },
  { key: "harlequin-s-caress", name: "Harlequin's caress", points: 3, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -2, damage: "1", abilities: "" },
  { key: "harlequin-s-embrace", name: "Harlequin's embrace", points: 2, range: "Melee", weaponType: "melee", attacks: "1", strength: "+1", ap: -3, damage: "1", abilities: "" },
  { key: "harlequin-s-kiss", name: "Harlequin's kiss", points: 4, range: "Melee", weaponType: "melee", attacks: "1", strength: "+1", ap: -1, damage: "D3", abilities: "" },
  { key: "miststave", name: "Miststave", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -1, damage: "D3", abilities: "" },
  { key: "power-sword", name: "Power sword", points: 4, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -3, damage: "1", abilities: "" }
];

export const HARLEQUINS_MODELS = [
  { key: "death-jester", name: "Death Jester", points: 45, maxNumber: "1", profile: { move: "8\"", ws: 2, bs: 2, strength: 3, toughness: 3, wounds: 5, attacks: 4, ld: 9, save: 6 }, keywords: "Harlequins, Aeldari, Infantry, Death Jester", wargear: "Shrieker Cannon", specialisms: [
      "Ferocity",
      "Melee",
      "Shooting",
      "Stealth"
    ], commander: true, abilities: [] },
  { key: "player", name: "Player", points: 12, maxNumber: "-", profile: { move: "8\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 1, attacks: 4, ld: 8, save: 6 }, keywords: "Harlequins, Aeldari, Infantry, Player", wargear: "", specialisms: [
      "Combat",
      "Medic",
      "Scout",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [] },
  { key: "shadowseer", name: "Shadowseer", points: 65, maxNumber: "1", profile: { move: "8\"", ws: 2, bs: 2, strength: 3, toughness: 3, wounds: 5, attacks: 3, ld: 9, save: 6 }, keywords: "Harlequins, Aeldari, Infantry, Psyker, Shadowseer", wargear: "Hallucinogen grenade launcher; Miststave", specialisms: [
      "Ferocity",
      "Melee",
      "Psyker",
      "Shooting",
      "Stealth"
    ], commander: true, abilities: [] },
  { key: "troupe-master", name: "Troupe Master", points: 50, maxNumber: "1", profile: { move: "8\"", ws: 2, bs: 2, strength: 3, toughness: 3, wounds: 5, attacks: 5, ld: 9, save: 6 }, keywords: "Harlequins, Aeldari, Infantry, Troupe Master", wargear: "Power sword", specialisms: [
      "Ferocity",
      "Leadership",
      "Melee",
      "Shooting",
      "Stealth",
      "Strategist"
    ], commander: true, abilities: [] }
];

const FACTION = "Harlequins";

export const HARLEQUINS_ITEMS = HARLEQUINS_WEAPONS.map(w => ({ ...w, itemType: "weapon", faction: FACTION }));

export const HARLEQUINS_MODEL_ITEMS = HARLEQUINS_MODELS.map(m => ({ ...m, itemType: "model", faction: FACTION, rules: [] }));
