/**
 * Kroot.
 *
 * Generated by tools/import_catalogue.py from the New Recruit catalogue,
 * which tracks Kill Team 2018 including errata and the Elites and Commanders
 * expansions. Do not hand-edit: re-run the importer instead.
 *
 * 3 models, 4 weapons.
 *
 * Ability text is imported as prose. Machine-readable rules are tagged
 * separately, by hand, in module/rules/ - deciding what an ability does is a
 * judgement call and is not safe to automate.
 */

export const KROOT_WEAPONS = [
  { key: "kroot-gun", name: "Kroot gun", points: 0, range: "48\"", weaponType: "rapidFire", attacks: "1", strength: "7", ap: -1, damage: "D3", abilities: "" },
  { key: "kroot-pistol", name: "Kroot pistol", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "krootox-fists", name: "Krootox fists", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "2", abilities: "" },
  { key: "ripping-fangs", name: "Ripping fangs", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "1", abilities: "" }
];

export const KROOT_MODELS = [
  { key: "dahyak-grekh", name: "Dahyak Grekh", points: 25, maxNumber: "1", profile: { move: "7\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 3, attacks: 3, ld: 7, save: 6 }, keywords: "Kroot, Commander, Infantry, Dahyak Grekh", wargear: "Kroot pistol", specialisms: [], commander: true, abilities: [] },
  { key: "kroot-hound", name: "Kroot Hound", points: 6, maxNumber: "4", profile: { move: "12\"", ws: 3, bs: 4, strength: 3, toughness: 3, wounds: 1, attacks: 2, ld: 5, save: 6 }, keywords: "Kroot, Beast, Kroot Hound", wargear: "Ripping fangs", specialisms: [
      "Combat",
      "Scout"
    ], commander: false, abilities: [] },
  { key: "krootox-rider", name: "Krootox Rider", points: 27, maxNumber: "1", profile: { move: "7\"", ws: 3, bs: 4, strength: 6, toughness: 5, wounds: 4, attacks: 2, ld: 6, save: 6 }, keywords: "Kroot, Krootox Rider, Cavalry", wargear: "Kroot gun; Krootox fists", specialisms: [
      "Combat",
      "Veteran"
    ], commander: false, abilities: [] }
];

const FACTION = "Kroot";

export const KROOT_ITEMS = KROOT_WEAPONS.map(w => ({ ...w, itemType: "weapon", faction: FACTION }));

export const KROOT_MODEL_ITEMS = KROOT_MODELS.map(m => ({ ...m, itemType: "model", faction: FACTION, rules: [] }));
