/**
 * Necrons.
 *
 * Generated by tools/import_catalogue.py from the New Recruit catalogue,
 * which tracks Kill Team 2018 including errata and the Elites and Commanders
 * expansions. Do not hand-edit: re-run the importer instead.
 *
 * 13 models, 26 weapons.
 *
 * Ability text is imported as prose. Machine-readable rules are tagged
 * separately, by hand, in module/rules/ - deciding what an ability does is a
 * judgement call and is not safe to automate.
 */

export const NECRONS_WEAPONS = [
  { key: "abyssal-lance-shooting", name: "Abyssal lance (shooting)", points: 0, range: "18\"", weaponType: "assault", attacks: "3", strength: "4", ap: -3, damage: "1", abilities: "" },
  { key: "aeonstave-shooting", name: "Aeonstave (shooting)", points: 0, range: "18\"", weaponType: "assault", attacks: "D3", strength: "5", ap: -2, damage: "1", abilities: "When attacking with this weapon, an invulnerable save cannot be used." },
  { key: "entropic-lance-shooting", name: "Entropic lance (shooting)", points: 0, range: "18\"", weaponType: "assault", attacks: "1", strength: "8", ap: -3, damage: "D6", abilities: "" },
  { key: "gauss-blaster", name: "Gauss Blaster", points: 0, range: "30\"", weaponType: "rapidFire", attacks: "1", strength: "5", ap: -2, damage: "1", abilities: "" },
  { key: "gauss-flayer", name: "Gauss flayer", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "1", strength: "4", ap: -1, damage: "1", abilities: "" },
  { key: "gauss-reaper", name: "Gauss reaper", points: 0, range: "12\"", weaponType: "assault", attacks: "2", strength: "5", ap: -2, damage: "1", abilities: "" },
  { key: "particle-caster", name: "Particle caster", points: 0, range: "12\"", weaponType: "pistol", attacks: "2", strength: "6", ap: 0, damage: "1", abilities: "" },
  { key: "plasmic-lance-shooting", name: "Plasmic lance (shooting)", points: 0, range: "18\"", weaponType: "assault", attacks: "D3", strength: "7", ap: -3, damage: "2", abilities: "" },
  { key: "relic-gauss-blaster", name: "Relic gauss blaster", points: 0, range: "30\"", weaponType: "rapidFire", attacks: "2", strength: "5", ap: -2, damage: "2", abilities: "" },
  { key: "rod-of-covenant-ranged", name: "Rod of covenant (ranged)", points: 0, range: "12\"", weaponType: "assault", attacks: "1", strength: "5", ap: -3, damage: "2", abilities: "" },
  { key: "staff-of-light-ranged", name: "Staff of light (ranged)", points: 0, range: "12\"", weaponType: "assault", attacks: "3", strength: "5", ap: -2, damage: "1", abilities: "" },
  { key: "synaptic-disintegrator", name: "Synaptic disintegrator", points: 0, range: "36\"", weaponType: "heavy", attacks: "1", strength: "5", ap: -2, damage: "1", abilities: "A model firing a synaptic disintegrator does not suffer the penalty to hit rolls for the target being at long range. Each time you roll a wound roll of 6+ for this weapon, the target suffers a mortal wound in addition to any other damage." },
  { key: "tesla-carbine", name: "Tesla Carbine", points: 0, range: "24\"", weaponType: "assault", attacks: "2", strength: "5", ap: 0, damage: "1", abilities: "Each unmodified hit roll of 6 with this weapon causes 3 hits." },
  { key: "abyssal-lance-melee", name: "Abyssal lance (melee)", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -3, damage: "1", abilities: "" },
  { key: "aeonstave-melee", name: "Aeonstave (melee)", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -2, damage: "1", abilities: "When attacking with this weapon, an invulnerable save cannot be used." },
  { key: "chronotendrils", name: "Chronotendrils", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "When the bearer fights, it can make 3 additional attacks with this weapon." },
  { key: "entropic-lance-melee", name: "Entropic lance (melee)", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -3, damage: "3", abilities: "" },
  { key: "flayer-claws", name: "Flayer Claws", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "1", abilities: "" },
  { key: "hyperphase-glaive-and-tachyon-arrow", name: "Hyperphase glaive and tachyon arrow", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -3, damage: "D3", abilities: "" },
  { key: "hyperphase-sword", name: "Hyperphase sword", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+1", ap: -3, damage: "1", abilities: "" },
  { key: "plasmic-lance-melee", name: "Plasmic lance (melee)", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -3, damage: "2", abilities: "" },
  { key: "rod-of-covenant-melee", name: "Rod of covenant (melee)", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -3, damage: "2", abilities: "" },
  { key: "staff-of-light-melee", name: "Staff of light (melee)", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -2, damage: "1", abilities: "" },
  { key: "voidblade", name: "Voidblade", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -3, damage: "1", abilities: "Each time the bearer fights, it can make 1 additional attack with this weapon." },
  { key: "voidscythe", name: "Voidscythe", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -4, damage: "3", abilities: "When attacking with this weapon, subtract 1 from the hit roll." },
  { key: "warscythe", name: "Warscythe", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -4, damage: "2", abilities: "" }
];

export const NECRONS_MODELS = [
  { key: "ankra-the-colossus", name: "Ankra the Colossus", points: 86, maxNumber: "1", profile: { move: "5\"", ws: 2, bs: 2, strength: 5, toughness: 6, wounds: 5, attacks: 3, ld: 10, save: 3 }, keywords: "Necrons, New CategoryLink, Infantry, Overlord, Level 1, Level 2, Level 3, Level 4", wargear: "Level 1 - Impenetrable; Level 2 - Bloodthirsty; Level 3 - Vengeful; Level 4 - Ancient Strategist; Voidscythe", specialisms: [], commander: false, abilities: [
      "Living Metal: At the beginning of each battle round, this model recovers 1 wound lost earlier in the battle."
    ] },
  { key: "chronomancer", name: "Chronomancer", points: 44, maxNumber: "1", profile: { move: "8\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 4, attacks: 1, ld: 10, save: 4 }, keywords: "Necrons, New CategoryLink, Infantry, Chronomancer", wargear: "Aeonstave; Chronotendrils; Entropic lance", specialisms: [
      "Fortitude",
      "Logistics",
      "Melee",
      "Shooting",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "Living Metal: At the beginning of each battle round, this model recovers 1 wound lost earlier in the battle."
    ] },
  { key: "deathmark", name: "Deathmark", points: 16, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 2, strength: 4, toughness: 5, wounds: 1, attacks: 1, ld: 10, save: 3 }, keywords: "Necrons, Infantry, Deathmark", wargear: "Synaptic disintegrator", specialisms: [
      "Comms",
      "Scout",
      "Sniper",
      "Veteran"
    ], commander: false, abilities: [
      "Reanimation Protocols: When an Injury roll is made for this model, on an unmodified roll of 6 the model is not taken out of action and does not suffer a flesh wound.  Instead it is restored to 1 wound remaining with no flesh wounds."
    ] },
  { key: "flayed-one", name: "Flayed One", points: 10, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 6, strength: 4, toughness: 4, wounds: 1, attacks: 3, ld: 10, save: 4 }, keywords: "Necrons, Infantry, Flayed One", wargear: "Flayer Claws", specialisms: [
      "Combat",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Reanimation Protocols: When an Injury roll is made for this model, on an unmodified roll of 6 the model is not taken out of action and does not suffer a flesh wound.  Instead it is restored to 1 wound remaining with no flesh wounds."
    ] },
  { key: "immortal", name: "Immortal", points: 17, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 5, wounds: 1, attacks: 2, ld: 10, save: 3 }, keywords: "Necrons, Infantry, Immortal", wargear: "Gauss Blaster; Tesla Carbine", specialisms: [
      "Comms",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Reanimation Protocols: When an Injury roll is made for this model, on an unmodified roll of 6 the model is not taken out of action and does not suffer a flesh wound.  Instead it is restored to 1 wound remaining with no flesh wounds."
    ] },
  { key: "lychguard", name: "Lychguard", points: 22, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 3, strength: 5, toughness: 5, wounds: 2, attacks: 3, ld: 10, save: 3 }, keywords: "Necrons, Infantry, Lychguard", wargear: "Hyperphase sword and dispersion shield; Warscythe", specialisms: [
      "Combat",
      "Comms",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Reanimation Protocols: When an Injury roll is made for this model, on an unmodified roll of 6 the model is not taken out of action and does not suffer a flesh wound.  Instead it is restored to 1 wound remaining with no flesh wounds."
    ] },
  { key: "necron-warrior", name: "Necron Warrior", points: 12, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 1, attacks: 1, ld: 10, save: 4 }, keywords: "Necrons, Infantry, Necron Warrior", wargear: "Gauss flayer; Gauss reaper", specialisms: [
      "Comms",
      "Veteran"
    ], commander: false, abilities: [
      "Reanimation Protocols: When an Injury roll is made for this model, on an unmodified roll of 6 the model is not taken out of action and does not suffer a flesh wound.  Instead it is restored to 1 wound remaining with no flesh wounds."
    ] },
  { key: "overlord", name: "Overlord", points: 86, maxNumber: "1", profile: { move: "5\"", ws: 2, bs: 2, strength: 5, toughness: 5, wounds: 5, attacks: 4, ld: 10, save: 3 }, keywords: "Necrons, Commander, Infantry, Overlord", wargear: "Hyperphase glaive and tachyon arrow; Resurrection orb; Voidscythe; Warscythe", specialisms: [
      "Fortitude",
      "Leadership",
      "Logistics",
      "Melee",
      "Shooting",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "Living Metal: At the beginning of each battle round, this model recovers 1 wound lost earlier in the battle."
    ] },
  { key: "plasmancer", name: "Plasmancer", points: 44, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 4, attacks: 1, ld: 10, save: 4 }, keywords: "Necrons, New CategoryLink, Infantry, Cryptek, Plasmancer", wargear: "Plasmic lance", specialisms: [
      "Fortitude",
      "Logistics",
      "Melee",
      "Shooting",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "Living Metal: At the beginning of each battle round, this model recovers 1 wound lost earlier in the battle."
    ] },
  { key: "psychomancer", name: "Psychomancer", points: 44, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 4, attacks: 1, ld: 10, save: 4 }, keywords: "Necrons, New CategoryLink, Infantry, Cryptek, Psychomancer", wargear: "Abyssal lance", specialisms: [
      "Fortitude",
      "Logistics",
      "Melee",
      "Shooting",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "Living Metal: At the beginning of each battle round, this model recovers 1 wound lost earlier in the battle."
    ] },
  { key: "royal-warden", name: "Royal Warden", points: 46, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 3, strength: 5, toughness: 5, wounds: 4, attacks: 3, ld: 10, save: 3 }, keywords: "Necrons, New CategoryLink, Infantry, Royal Warden", wargear: "Relic gauss blaster", specialisms: [
      "Fortitude",
      "Leadership",
      "Logistics",
      "Shooting",
      "Strategist"
    ], commander: true, abilities: [
      "Living Metal: At the beginning of each battle round, this model recovers 1 wound lost earlier in the battle."
    ] },
  { key: "technomancer", name: "Technomancer", points: 44, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 4, attacks: 1, ld: 10, save: 4 }, keywords: "Necrons, New CategoryLink, Infantry, Cryptek, Technomancer, Fly", wargear: "Canoptek cloak", specialisms: [
      "Fortitude",
      "Logistics",
      "Melee",
      "Shooting",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "Living Metal: At the beginning of each battle round, this model recovers 1 wound lost earlier in the battle."
    ] },
  { key: "triarch-praetorian", name: "Triarch Praetorian", points: 28, maxNumber: "-", profile: { move: "10\"", ws: 3, bs: 3, strength: 5, toughness: 5, wounds: 2, attacks: 3, ld: 10, save: 3 }, keywords: "Necrons, Infantry, Fly, Triarch Praetorian", wargear: "Rod of covenant; Voidblade and particle caster", specialisms: [
      "Combat",
      "Comms",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Reanimation Protocols: When an Injury roll is made for this model, on an unmodified roll of 6 the model is not taken out of action and does not suffer a flesh wound.  Instead it is restored to 1 wound remaining with no flesh wounds."
    ] }
];

const FACTION = "Necrons";

export const NECRONS_ITEMS = NECRONS_WEAPONS.map(w => ({ ...w, itemType: "weapon", faction: FACTION }));

export const NECRONS_MODEL_ITEMS = NECRONS_MODELS.map(m => ({ ...m, itemType: "model", faction: FACTION, rules: [] }));
