/**
 * Orks.
 *
 * Generated by tools/import_catalogue.py from the New Recruit catalogue,
 * which tracks Kill Team 2018 including errata and the Elites and Commanders
 * expansions. Do not hand-edit: re-run the importer instead.
 *
 * 23 models, 29 weapons.
 *
 * Ability text is imported as prose. Machine-readable rules are tagged
 * separately, by hand, in module/rules/ - deciding what an ability does is a
 * judgement call and is not safe to automate.
 */

export const ORKS_WEAPONS = [
  { key: "big-shoota", name: "Big Shoota", points: 0, range: "36\"", weaponType: "assault", attacks: "3", strength: "5", ap: 0, damage: "1", abilities: "" },
  { key: "burna-ranged", name: "Burna (Ranged)", points: 0, range: "8\"", weaponType: "assault", attacks: "D3", strength: "4", ap: 0, damage: "1", abilities: "This weapon automatically hits its target." },
  { key: "deffgun", name: "Deffgun", points: 0, range: "48\"", weaponType: "heavy", attacks: "D3", strength: "7", ap: -1, damage: "2", abilities: "" },
  { key: "grot-blasta", name: "Grot Blasta", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "3", ap: 0, damage: "1", abilities: "" },
  { key: "kombi-weapon", name: "Kombi-weapon", points: 0, range: "-", weaponType: "assault", attacks: "1", strength: "-", ap: 0, damage: "-", abilities: "When attacking with this weapon, choose one or more of the profiles. If you choose both, subtract 1 from all hit rolls made for this weapon." },
  { key: "kombi-weapon-with-skorcha-shoota", name: "Kombi-weapon with Skorcha (Shoota)", points: 0, range: "18\"", weaponType: "assault", attacks: "2", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "kombi-weapon-with-skorcha-skorcha", name: "Kombi-weapon with Skorcha (Skorcha)", points: 0, range: "8\"", weaponType: "assault", attacks: "D6", strength: "5", ap: -1, damage: "1", abilities: "This weapon automatically hits its target." },
  { key: "kombi-weapon-with-rokkit-launcha-rokkit-launcha", name: "Kombi-weapon with rokkit launcha (Rokkit Launcha)", points: 0, range: "24\"", weaponType: "assault", attacks: "1", strength: "8", ap: -2, damage: "3", abilities: "" },
  { key: "kombi-weapon-with-rokkit-launcha-shoota", name: "Kombi-weapon with rokkit launcha (Shoota)", points: 0, range: "18\"", weaponType: "assault", attacks: "2", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "kustom-mega-slugga", name: "Kustom Mega-Slugga", points: 4, range: "12\"", weaponType: "pistol", attacks: "1", strength: "8", ap: -3, damage: "D3", abilities: "On an unmodified roll of 1, the bearer is taken out of action." },
  { key: "kustom-mega-blasta", name: "Kustom Mega-blasta", points: 0, range: "24", weaponType: "assault", attacks: "1", strength: "8", ap: -3, damage: "D3", abilities: "On an unmodified hit roll of 1, the bearer suffers a mortal wound." },
  { key: "kustom-shoota", name: "Kustom Shoota", points: 0, range: "24\"", weaponType: "assault", attacks: "4", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "kustom-grot-blasta", name: "Kustom grot blasta", points: 0, range: "12\"", weaponType: "pistol", attacks: "D3", strength: "5", ap: -1, damage: "2", abilities: "" },
  { key: "rokkit-launcha", name: "Rokkit Launcha", points: 3, range: "24\"", weaponType: "assault", attacks: "1", strength: "8", ap: -2, damage: "3", abilities: "" },
  { key: "shokk-attack-gun", name: "Shokk Attack Gun", points: 27, range: "60\"", weaponType: "heavy", attacks: "D6", strength: "2D6", ap: -5, damage: "D3", abilities: "Before firing this weapon, roll once to determine the Strength of all its shots. If the result is 11+, do not make wound rolls - instead, each attack that hits causes D3 mortal wounds." },
  { key: "shoota", name: "Shoota", points: 0, range: "18\"", weaponType: "assault", attacks: "2", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "slugga", name: "Slugga", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "snazzgun", name: "Snazzgun", points: 0, range: "24\"", weaponType: "heavy", attacks: "3", strength: "6", ap: -2, damage: "2", abilities: "" },
  { key: "stikkbombs", name: "Stikkbombs", points: 0, range: "6\"", weaponType: "grenade", attacks: "D6", strength: "3", ap: 0, damage: "1", abilities: "" },
  { key: "urty-syringe", name: "'Urty Syringe", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "This weapon always wounds on a roll of 2+." },
  { key: "attack-squig", name: "Attack Squig", points: 6, range: "Melee", weaponType: "melee", attacks: "1", strength: "4", ap: -1, damage: "1", abilities: "Each time a model with an attack squig fights, it can make 2 additional attacks with this weapon." },
  { key: "big-choppa", name: "Big Choppa", points: 3, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -1, damage: "2", abilities: "" },
  { key: "burna-melee", name: "Burna (Melee)", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -2, damage: "1", abilities: "" },
  { key: "choppa", name: "Choppa", points: 1, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "Each time the bearer fights, it can make 1 additional attack with this weapon." },
  { key: "icon-of-da-revolushun", name: "Icon of da Revolushun", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "1", abilities: "For each wound roll of 6+ made for this weapon, the target model suffers 1 mortal wound in addition to the normal damage." },
  { key: "killsaw", name: "Killsaw", points: 5, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -4, damage: "2", abilities: "When attacking with this weapon, you must subtract 1 from the hit roll. If a model is armed with two killsaws, add 1 to its Attacks characteristic." },
  { key: "mork-s-tooth", name: "Mork's Tooth", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "2", abilities: "" },
  { key: "power-klaw", name: "Power Klaw", points: 5, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -3, damage: "D3", abilities: "When attacking with this weapon, you must subtract 1 from the hit roll." },
  { key: "power-stabba", name: "Power stabba", points: 1, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -2, damage: "1", abilities: "" }
];

export const ORKS_MODELS = [
  { key: "ammo-runt", name: "Ammo Runt", points: 3, maxNumber: "2", profile: { move: "5\"", ws: 5, bs: 4, strength: 3, toughness: 3, wounds: 1, attacks: 1, ld: 4, save: 6 }, keywords: "Orks, Infantry, Gretchin", wargear: "", specialisms: [], commander: false, abilities: [] },
  { key: "big-mek", name: "Big Mek", points: 20, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 5, strength: 5, toughness: 4, wounds: 4, attacks: 3, ld: 7, save: 4 }, keywords: "Orks, Commander, Infantry, Big Mek", wargear: "Kustom force field", specialisms: [
      "Ferocity",
      "Fortitude",
      "Logistics",
      "Melee",
      "Strength"
    ], commander: true, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability."
    ] },
  { key: "boss-meganob", name: "Boss Meganob", points: 41, maxNumber: "1", profile: { move: "4\"", ws: 3, bs: 5, strength: 5, toughness: 4, wounds: 3, attacks: 3, ld: 7, save: 2 }, keywords: "Orks, Infantry, Mega Armour, Nob, Meganob", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Veteran"
    ], commander: false, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability.",
      "Keepin' Order: When you make an unmodified roll of 6 for a Nerve test taken for a model within 3\" of a friendly model with this ability, that Nerve test is passed."
    ] },
  { key: "boss-nob-boyz", name: "Boss Nob (Boyz)", points: 10, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 5, strength: 5, toughness: 4, wounds: 2, attacks: 3, ld: 7, save: 6 }, keywords: "Orks, Infantry, Ork Boy", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Veteran"
    ], commander: false, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability."
    ] },
  { key: "boss-nob-nobs", name: "Boss Nob (Nobs)", points: 16, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 5, strength: 5, toughness: 4, wounds: 2, attacks: 3, ld: 7, save: 4 }, keywords: "Orks, Infantry, Nob", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Veteran"
    ], commander: false, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability.",
      "Keepin' Order: When you make an unmodified roll of 6 for a Nerve test taken for a model within 3\" of a friendly model with this ability, that Nerve test is passed."
    ] },
  { key: "boss-snikrot", name: "Boss Snikrot", points: 82, maxNumber: "1", profile: { move: "6\"", ws: 2, bs: 5, strength: 6, toughness: 4, wounds: 6, attacks: 6, ld: 7, save: 6 }, keywords: "Orks, Infantry, Kommando, Boss Snikrot", wargear: "Mork's Tooth", specialisms: [], commander: false, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability."
    ] },
  { key: "burna-boy", name: "Burna Boy", points: 12, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 5, strength: 4, toughness: 4, wounds: 1, attacks: 2, ld: 6, save: 6 }, keywords: "Orks, Burna Boy, Infantry", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability."
    ] },
  { key: "burna-spanner", name: "Burna Spanner", points: 10, maxNumber: "3", profile: { move: "5\"", ws: 3, bs: 5, strength: 4, toughness: 4, wounds: 1, attacks: 2, ld: 6, save: 6 }, keywords: "Orks, Burna Boy, Infantry", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability."
    ] },
  { key: "da-red-gobbo", name: "Da Red Gobbo", points: 43, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 3, strength: 3, toughness: 3, wounds: 5, attacks: 4, ld: 7, save: 4 }, keywords: "Orks, Infantry, Gretchin, Da Red Gobbo", wargear: "Icon of da Revolushun; Kustom grot blasta", specialisms: [], commander: false, abilities: [] },
  { key: "flash-git", name: "Flash Git", points: 23, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 4, strength: 5, toughness: 4, wounds: 2, attacks: 3, ld: 6, save: 4 }, keywords: "Orks, Infantry, Flash Git, Freebooterz", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Heavy",
      "Veteran"
    ], commander: false, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability.",
      "Gun-crazy Show-off: After this model has shot in the Shooting phase, roll a D6. On a 6, this model can immediately shoot again, but can only target the nearest enemy model."
    ] },
  { key: "gitzog-wurldkilla", name: "Gitzog Wurldkilla", points: 86, maxNumber: "1", profile: { move: "5\"", ws: 2, bs: 5, strength: 6, toughness: 6, wounds: 6, attacks: 4, ld: 8, save: 4 }, keywords: "Orks, Infantry, Warboss, Level 1, Level 2, Level 3, Level 4", wargear: "Level 1 - Dead 'Ard; Level 2 - Redfangz Smellz Yer!; Level 3 - Krumpin' Time; Level 4 - Loota", specialisms: [], commander: false, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability."
    ] },
  { key: "gretchin", name: "Gretchin", points: 3, maxNumber: "-", profile: { move: "5", ws: 5, bs: 4, strength: 2, toughness: 2, wounds: 1, attacks: 1, ld: 4, save: 6 }, keywords: "Orks, Infantry, Gretchin", wargear: "", specialisms: [], commander: false, abilities: [] },
  { key: "kaptin", name: "Kaptin", points: 24, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 4, strength: 5, toughness: 4, wounds: 2, attacks: 3, ld: 6, save: 4 }, keywords: "Orks, Freebootaz, Infantry, Flash Git", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Heavy",
      "Veteran"
    ], commander: false, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability.",
      "Gun-crazy Show-off: After this model has shot in the Shooting phase, roll a D6. On a 6, this model can immediately shoot again, but can only target the nearest enemy model."
    ] },
  { key: "kommando", name: "Kommando", points: 8, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 5, strength: 4, toughness: 4, wounds: 1, attacks: 2, ld: 6, save: 6 }, keywords: "Orks, Infantry, Kommando", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Scout",
      "Veteran"
    ], commander: false, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability.",
      "Sneaky Gits: When an enemy player makes a hit roll for a shooting attack that targets this model, and this model is obscurred, that hit roll suffers and additional -1 modifier."
    ] },
  { key: "kommando-boss-nob", name: "Kommando Boss Nob", points: 12, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 5, strength: 5, toughness: 4, wounds: 2, attacks: 3, ld: 7, save: 6 }, keywords: "Orks, Infantry, Kommando", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Scout",
      "Veteran"
    ], commander: false, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability.",
      "Sneaky Gits: When an enemy player makes a hit roll for a shooting attack that targets this model, and this model is obscurred, that hit roll suffers and additional -1 modifier."
    ] },
  { key: "loota", name: "Loota", points: 12, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 5, strength: 4, toughness: 4, wounds: 1, attacks: 2, ld: 6, save: 6 }, keywords: "Orks, Infantry, Loota", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Heavy",
      "Veteran"
    ], commander: false, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability."
    ] },
  { key: "loota-spanner", name: "Loota Spanner", points: 10, maxNumber: "3", profile: { move: "5\"", ws: 3, bs: 5, strength: 4, toughness: 4, wounds: 1, attacks: 2, ld: 6, save: 6 }, keywords: "Orks, Infantry, Loota", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Heavy",
      "Veteran"
    ], commander: false, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability."
    ] },
  { key: "meganob", name: "Meganob", points: 37, maxNumber: "-", profile: { move: "4\"", ws: 3, bs: 5, strength: 5, toughness: 4, wounds: 3, attacks: 3, ld: 6, save: 2 }, keywords: "Orks, Infantry, Mega Armour, Nob, Meganob", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Veteran"
    ], commander: false, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability.",
      "Keepin' Order: When you make an unmodified roll of 6 for a Nerve test taken for a model within 3\" of a friendly model with this ability, that Nerve test is passed."
    ] },
  { key: "nob", name: "Nob", points: 15, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 5, strength: 5, toughness: 4, wounds: 2, attacks: 3, ld: 6, save: 4 }, keywords: "Orks, Infantry, Nob", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Veteran"
    ], commander: false, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability.",
      "Keepin' Order: When you make an unmodified roll of 6 for a Nerve test taken for a model within 3\" of a friendly model with this ability, that Nerve test is passed."
    ] },
  { key: "ork-boy", name: "Ork Boy", points: 6, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 5, strength: 4, toughness: 4, wounds: 1, attacks: 2, ld: 6, save: 6 }, keywords: "Orks, Infantry, Ork Boy", wargear: "Shoota; Slugga and Choppa", specialisms: [
      "Combat",
      "Demolitions",
      "Veteran"
    ], commander: false, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability."
    ] },
  { key: "ork-boy-gunner", name: "Ork Boy Gunner", points: 7, maxNumber: "2", profile: { move: "5\"", ws: 3, bs: 5, strength: 4, toughness: 4, wounds: 1, attacks: 2, ld: 6, save: 6 }, keywords: "Orks, Infantry, Ork Boy", wargear: "Slugga and Choppa", specialisms: [
      "Combat",
      "Demolitions",
      "Heavy",
      "Veteran"
    ], commander: false, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability."
    ] },
  { key: "painboy", name: "Painboy", points: 20, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 5, strength: 5, toughness: 4, wounds: 4, attacks: 4, ld: 6, save: 6 }, keywords: "Orks, Commander, Infantry, Painboy", wargear: "", specialisms: [
      "Ferocity",
      "Fortitude",
      "Logistics",
      "Melee",
      "Strength"
    ], commander: true, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability."
    ] },
  { key: "warboss", name: "Warboss", points: 62, maxNumber: "1", profile: { move: "5\"", ws: 2, bs: 5, strength: 6, toughness: 5, wounds: 6, attacks: 4, ld: 8, save: 4 }, keywords: "Orks, Commander, Infantry, Warboss", wargear: "", specialisms: [
      "Ferocity",
      "Fortitude",
      "Leadership",
      "Melee",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "'Ere We Go: Re-roll failed charge rolls for a unit with this ability."
    ] }
];

const FACTION = "Orks";

export const ORKS_ITEMS = ORKS_WEAPONS.map(w => ({ ...w, itemType: "weapon", faction: FACTION }));

export const ORKS_MODEL_ITEMS = ORKS_MODELS.map(m => ({ ...m, itemType: "model", faction: FACTION, rules: [] }));
