/**
 * Space Marines.
 *
 * Generated by tools/import_catalogue.py from the New Recruit catalogue,
 * which tracks Kill Team 2018 including errata and the Elites and Commanders
 * expansions. Do not hand-edit: re-run the importer instead.
 *
 * 50 models, 82 weapons.
 *
 * Ability text is imported as prose. Machine-readable rules are tagged
 * separately, by hand, in module/rules/ - deciding what an ability does is a
 * judgement call and is not safe to automate.
 */

export const SPACE_MARINES_WEAPONS = [
  { key: "absolvor-bolt-pistol", name: "Absolvor bolt pistol", points: 0, range: "18\"", weaponType: "pistol", attacks: "1", strength: "5", ap: -1, damage: "2", abilities: "" },
  { key: "accelerator-autocannon", name: "Accelerator autocannon", points: 0, range: "48\"", weaponType: "heavy", attacks: "3", strength: "7", ap: -1, damage: "2", abilities: "If this weapon inflicts any damage on an enemy model, until the end of the battle round that model and enemy models within 2\" of that model cannot make shooting attacks." },
  { key: "assault-cannon", name: "Assault cannon", points: 5, range: "24\"", weaponType: "heavy", attacks: "6", strength: "6", ap: -1, damage: "1", abilities: "" },
  { key: "auto-bolt-rifle", name: "Auto bolt rifle", points: 0, range: "24\"", weaponType: "assault", attacks: "3", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "bolt-carbine", name: "Bolt carbine", points: 0, range: "24\"", weaponType: "assault", attacks: "2", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "bolt-pistol", name: "Bolt pistol", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "bolt-rifle", name: "Bolt rifle", points: 0, range: "30\"", weaponType: "rapidFire", attacks: "1", strength: "4", ap: -1, damage: "1", abilities: "" },
  { key: "bolt-sniper-rifle-executioner-round", name: "Bolt sniper rifle - Executioner round", points: 0, range: "36\"", weaponType: "heavy", attacks: "1", strength: "5", ap: -1, damage: "1", abilities: "Add 1 to hit rolls for this weapon. Add an additional 1 to hit rolls when targeting a model that is obscured." },
  { key: "bolt-sniper-rifle-hyperfrag-round", name: "Bolt sniper rifle - Hyperfrag round", points: 0, range: "36\"", weaponType: "heavy", attacks: "D3", strength: "5", ap: 0, damage: "1", abilities: "" },
  { key: "bolt-sniper-rifle-mortis-round", name: "Bolt sniper rifle - Mortis round", points: 0, range: "36\"", weaponType: "heavy", attacks: "1", strength: "5", ap: -2, damage: "2", abilities: "If you make an unmodified wound roll of 6 for this weapon, it inflicts a mortal wound in addition to the normal damage." },
  { key: "boltgun", name: "Boltgun", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "1", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "boltstorm-gauntlet-ranged", name: "Boltstorm gauntlet (ranged)", points: 0, range: "12\"", weaponType: "pistol", attacks: "3", strength: "4", ap: -1, damage: "1", abilities: "" },
  { key: "combi-bolter", name: "Combi-bolter", points: 2, range: "24\"", weaponType: "rapidFire", attacks: "2", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "cyclone-missile-launcher", name: "Cyclone missile launcher", points: 6, range: "-", weaponType: "assault", attacks: "1", strength: "", ap: 0, damage: "-", abilities: "When attacking with this weapon, choose one of the profiles below." },
  { key: "cyclone-missile-launcher-frag-missile", name: "Cyclone missile launcher - Frag missile", points: 0, range: "36\"", weaponType: "heavy", attacks: "2D6", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "cyclone-missile-launcher-krak-missile", name: "Cyclone missile launcher - Krak missile", points: 0, range: "36\"", weaponType: "heavy", attacks: "2", strength: "8", ap: -2, damage: "D6", abilities: "" },
  { key: "executor-bolt-rifle", name: "Executor bolt rifle", points: 0, range: "42\"", weaponType: "heavy", attacks: "1", strength: "5", ap: -2, damage: "2", abilities: "" },
  { key: "executor-heavy-bolter", name: "Executor heavy bolter", points: 7, range: "42\"", weaponType: "heavy", attacks: "2", strength: "5", ap: -2, damage: "3", abilities: "" },
  { key: "flamer", name: "Flamer", points: 3, range: "12\"", weaponType: "assault", attacks: "D6", strength: "4", ap: 0, damage: "1", abilities: "This weapon automatically hits its target." },
  { key: "frag-grenade", name: "Frag grenade", points: 0, range: "6\"", weaponType: "grenade", attacks: "D6", strength: "3", ap: 0, damage: "1", abilities: "" },
  { key: "frag-missile", name: "Frag missile", points: 0, range: "48\"", weaponType: "heavy", attacks: "D6", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "grav-cannon-and-grav-amp", name: "Grav-cannon and grav-amp", points: 5, range: "30\"", weaponType: "heavy", attacks: "4", strength: "5", ap: -3, damage: "1", abilities: "If the target has a Save characteristic of 3+ or better, this weapon has a damage of 2." },
  { key: "grav-gun", name: "Grav-gun", points: 2, range: "18\"", weaponType: "rapidFire", attacks: "1", strength: "5", ap: -3, damage: "1", abilities: "If the target has a Save characteristic of 3+ or better, this weapon has a Damage characteristic of 2." },
  { key: "grav-pistol", name: "Grav-pistol", points: 1, range: "12\"", weaponType: "pistol", attacks: "1", strength: "5", ap: -3, damage: "1", abilities: "If the target has a Save characteristic of 3+ or better, this weapon has a Damage of 2." },
  { key: "hand-flamer", name: "Hand flamer", points: 0, range: "12\"", weaponType: "pistol", attacks: "D6", strength: "3", ap: 0, damage: "1", abilities: "This weapon automatically hits its target." },
  { key: "heavy-bolt-pistol", name: "Heavy bolt pistol", points: 0, range: "18\"", weaponType: "pistol", attacks: "1", strength: "4", ap: -1, damage: "1", abilities: "" },
  { key: "heavy-bolt-rifle", name: "Heavy bolt rifle", points: 0, range: "36\"", weaponType: "rapidFire", attacks: "1", strength: "5", ap: -1, damage: "1", abilities: "" },
  { key: "heavy-bolter", name: "Heavy bolter", points: 6, range: "36\"", weaponType: "heavy", attacks: "3", strength: "5", ap: -1, damage: "2", abilities: "" },
  { key: "heavy-flamer", name: "Heavy flamer", points: 5, range: "12\"", weaponType: "heavy", attacks: "D6", strength: "5", ap: -1, damage: "1", abilities: "This weapon automatically hits its target." },
  { key: "hellstorm-bolt-rifle", name: "Hellstorm bolt rifle", points: 0, range: "30\"", weaponType: "assault", attacks: "3", strength: "5", ap: 0, damage: "1", abilities: "" },
  { key: "hellstorm-heavy-bolter", name: "Hellstorm heavy bolter", points: 7, range: "30\"", weaponType: "heavy", attacks: "4", strength: "5", ap: 0, damage: "2", abilities: "" },
  { key: "inferno-pistol", name: "Inferno pistol", points: 8, range: "6\"", weaponType: "pistol", attacks: "1", strength: "8", ap: -4, damage: "D6", abilities: "When an attack made with this weapon hits a target that is within half range, that attack has a Damage characteristic of D6+2." },
  { key: "instigator-bolt-carbine", name: "Instigator bolt carbine", points: 0, range: "24\"", weaponType: "assault", attacks: "1", strength: "4", ap: -1, damage: "2", abilities: "" },
  { key: "krak-grenade", name: "Krak grenade", points: 0, range: "6\"", weaponType: "grenade", attacks: "1", strength: "6", ap: -1, damage: "D3", abilities: "" },
  { key: "krak-missile", name: "Krak missile", points: 0, range: "48\"", weaponType: "heavy", attacks: "1", strength: "8", ap: -2, damage: "D6", abilities: "" },
  { key: "las-fusil", name: "Las fusil", points: 5, range: "36\"", weaponType: "heavy", attacks: "1", strength: "8", ap: -3, damage: "3", abilities: "" },
  { key: "lascannon", name: "Lascannon", points: 13, range: "48\"", weaponType: "heavy", attacks: "1", strength: "9", ap: -3, damage: "D6", abilities: "" },
  { key: "marksman-bolt-carbine", name: "Marksman bolt carbine", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "1", strength: "4", ap: 0, damage: "1", abilities: "Each unmodified hit roll of 6 made for this weapon's attacks automatically results in a wound (do not make a wound roll for that attack)." },
  { key: "master-crafted-auto-bolt-rifle", name: "Master-crafted auto bolt rifle", points: 0, range: "24\"", weaponType: "assault", attacks: "3", strength: "4", ap: 0, damage: "2", abilities: "" },
  { key: "master-crafted-heavy-bolt-rifle", name: "Master-crafted heavy bolt rifle", points: 0, range: "36\"", weaponType: "rapidFire", attacks: "1", strength: "5", ap: -1, damage: "2", abilities: "" },
  { key: "master-crafted-instigator-bolt-rifle", name: "Master-crafted instigator bolt rifle", points: 0, range: "30\"", weaponType: "assault", attacks: "1", strength: "4", ap: -2, damage: "3", abilities: "A model firing this weapon does not suffer the penalty to hit rolls for the target being at long range." },
  { key: "master-crafted-occulus-bolt-carbine", name: "Master-crafted occulus bolt carbine", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "1", strength: "4", ap: 0, damage: "2", abilities: "Add 1 to hit rolls for this weapon when targeting a model that is obscured." },
  { key: "master-crafted-special-issue-bolt-pistol", name: "Master-crafted special issue bolt pistol", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "4", ap: -2, damage: "2", abilities: "" },
  { key: "master-crafted-stalker-bolt-rifle", name: "Master-crafted stalker bolt rifle", points: 0, range: "24\"", weaponType: "heavy", attacks: "1", strength: "4", ap: -2, damage: "3", abilities: "" },
  { key: "melta-bomb", name: "Melta bomb", points: 0, range: "4\"", weaponType: "grenade", attacks: "1", strength: "8", ap: -4, damage: "D6", abilities: "" },
  { key: "meltagun", name: "Meltagun", points: 7, range: "12\"", weaponType: "assault", attacks: "1", strength: "8", ap: -4, damage: "D6", abilities: "When an attack made with this weapon hits a target that is within half range, that attack has a Damage characteristic of D6+2." },
  { key: "multi-melta", name: "Multi-melta", points: 10, range: "24\"", weaponType: "heavy", attacks: "2", strength: "8", ap: -4, damage: "D6", abilities: "When an attack made with this weapon hits a target that is within half range, that attack has a Damage characteristic of D6+2." },
  { key: "neo-volkite-pistol", name: "Neo-volkite pistol", points: 0, range: "15\"", weaponType: "pistol", attacks: "2", strength: "5", ap: 0, damage: "2", abilities: "When making an attack with this weapon, an unmodified wound roll of 6 inflicts 1 mortal wound on the target in addition to the normal damage." },
  { key: "occulus-bolt-carbine", name: "Occulus bolt carbine", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "1", strength: "4", ap: 0, damage: "1", abilities: "Add 1 to hit rolls for this weapon when targeting a model that is obscured." },
  { key: "plasma-cannon-supercharge", name: "Plasma cannon - Supercharge", points: 0, range: "36\"", weaponType: "heavy", attacks: "D3", strength: "8", ap: -3, damage: "2", abilities: "On an unmodified hit roll of 1, the beaer is taken out of action after all of this weapon's shots have been resolved." },
  { key: "plasma-cannon-standard", name: "Plasma cannon - standard", points: 0, range: "36\"", weaponType: "heavy", attacks: "D3", strength: "7", ap: -3, damage: "1", abilities: "" },
  { key: "plasma-gun-standard", name: "Plasma gun - standard", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "1", strength: "7", ap: -3, damage: "1", abilities: "" },
  { key: "plasma-gun-supercharge", name: "Plasma gun - supercharge", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "1", strength: "8", ap: -3, damage: "2", abilities: "On an unmodified hit roll of 1, the bearer of this weapon is taken out of action after all this weapon's shots have been resolved." },
  { key: "plasma-pistol-standard", name: "Plasma pistol - standard", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "7", ap: -3, damage: "1", abilities: "" },
  { key: "plasma-pistol-supercharge", name: "Plasma pistol - supercharge", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "8", ap: -3, damage: "2", abilities: "On an unmodified hit roll of 1, the beaer is taken out of action after all of this weapon's shots have been resolved." },
  { key: "shock-grenade", name: "Shock grenade", points: 0, range: "6\"", weaponType: "grenade", attacks: "D3", strength: "*", ap: 0, damage: "*", abilities: "This weapon does not inflict any damage. If an enemy INFANTRY model is hit by any shock grenades, it is stunned; until the end of the next battle round that model cannot fire Overwatch or be Readied, and your opponent must subtract 1 from hit rolls made for the model." },
  { key: "special-issue-bolt-carbine", name: "Special-issue bolt carbine", points: 0, range: "24\"", weaponType: "assault", attacks: "2", strength: "4", ap: -2, damage: "2", abilities: "" },
  { key: "special-issue-bolt-pistol", name: "Special-issue bolt pistol", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "4", ap: -2, damage: "1", abilities: "" },
  { key: "special-issue-boltgun", name: "Special-issue boltgun", points: 0, range: "30\"", weaponType: "rapidFire", attacks: "1", strength: "4", ap: -2, damage: "1", abilities: "" },
  { key: "stalker-bolt-rifle", name: "Stalker bolt rifle", points: 0, range: "36\"", weaponType: "heavy", attacks: "1", strength: "4", ap: -2, damage: "2", abilities: "" },
  { key: "storm-bolter", name: "Storm bolter", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "2", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "wrist-mounted-grenade-launcher", name: "Wrist-mounted grenade launcher", points: 2, range: "12\"", weaponType: "assault", attacks: "D3", strength: "4", ap: -1, damage: "1", abilities: "" },
  { key: "astartes-chainsword", name: "Astartes chainsword", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "1", abilities: "Each time the bearer fights, it makes one additional attack with this weapon." },
  { key: "boltstorm-gauntlet-melee", name: "Boltstorm gauntlet (melee)", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -3, damage: "2", abilities: "When attacking with this weapon, subtract 1 from the hit roll." },
  { key: "chainfist", name: "Chainfist", points: 6, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -4, damage: "D3", abilities: "When making attacks with this weapon, you must subtract 1 from the hit roll." },
  { key: "combat-knife", name: "Combat knife", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "Each time the bearer fights, it can make 1 additional attack with this weapon." },
  { key: "crozius-arcanum", name: "Crozius arcanum", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -1, damage: "2", abilities: "" },
  { key: "executioner-relic-blade", name: "Executioner relic blade", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+3", ap: -3, damage: "2", abilities: "Each unmodified wound roll of 6 inflicts 1 mortal wound on the target in addition to any other damage." },
  { key: "force-axe", name: "Force axe", points: 2, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -2, damage: "D3", abilities: "" },
  { key: "force-stave", name: "Force stave", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+3", ap: -1, damage: "D3", abilities: "" },
  { key: "force-sword", name: "Force sword", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+1", ap: -3, damage: "D3", abilities: "" },
  { key: "heavy-thunder-hammer", name: "Heavy thunder hammer", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -3, damage: "4", abilities: "When attacking with this weapon, subtract 1 from the hit roll." },
  { key: "lightning-claw", name: "Lightning claw", points: 1, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -2, damage: "1", abilities: "Each time the bearer fights, it makes 1 additional attack with this weapon. When making an attack with this weapon, you can re-roll the wound roll." },
  { key: "master-crafted-power-axe", name: "Master-crafted power axe", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -2, damage: "2", abilities: "" },
  { key: "master-crafted-power-sword", name: "Master-crafted power sword", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+1", ap: -3, damage: "2", abilities: "" },
  { key: "paired-combat-blades", name: "Paired combat blades", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "1", abilities: "" },
  { key: "power-axe", name: "Power axe", points: 2, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -2, damage: "1", abilities: "" },
  { key: "power-fist", name: "Power fist", points: 4, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -3, damage: "2", abilities: "When attacking with this weapon, you must subtract 1 from the hit roll." },
  { key: "power-maul", name: "Power maul", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+3", ap: -1, damage: "1", abilities: "" },
  { key: "power-sword", name: "Power sword", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+1", ap: -3, damage: "1", abilities: "" },
  { key: "relic-blade", name: "Relic blade", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+3", ap: -3, damage: "2", abilities: "" },
  { key: "thunder-hammer", name: "Thunder hammer", points: 8, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -2, damage: "3", abilities: "When attacking with this weapon, you must subtract 1 from the hit roll." }
];

export const SPACE_MARINES_MODELS = [
  { key: "assault-intercessor", name: "Assault Intercessor", points: 15, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 7, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Primaris, Assault Intercessor", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "assault-intercessor-sergeant", name: "Assault Intercessor Sergeant", points: 16, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 3, ld: 8, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Primaris, Assault Intercessor", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "bladeguard-veteran", name: "Bladeguard Veteran", points: 24, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 3, attacks: 3, ld: 8, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Primaris, Bladeguard Veteran", wargear: "", specialisms: [], commander: false, abilities: [
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model."
    ] },
  { key: "bladeguard-veteran-sergeant", name: "Bladeguard Veteran Sergeant", points: 25, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 3, attacks: 4, ld: 9, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Primaris, Bladeguard Veteran", wargear: "", specialisms: [], commander: false, abilities: [
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model."
    ] },
  { key: "captain-in-gravis-armour", name: "Captain in Gravis Armour", points: 88, maxNumber: "1", profile: { move: "5\"", ws: 2, bs: 2, strength: 4, toughness: 5, wounds: 7, attacks: 5, ld: 9, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Primaris, Captain, Mk X Gravis", wargear: "Boltstorm gauntlet", specialisms: [
      "Ferocity",
      "Fortitude",
      "Leadership",
      "Logistics",
      "Melee",
      "Shooting",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "captain-in-phobos-armour", name: "Captain in Phobos Armour", points: 81, maxNumber: "1", profile: { move: "6\"", ws: 2, bs: 2, strength: 4, toughness: 4, wounds: 6, attacks: 5, ld: 9, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Primaris, Captain, Phobos", wargear: "Master-crafted instigator bolt rifle", specialisms: [
      "Ferocity",
      "Fortitude",
      "Leadership",
      "Logistics",
      "Melee",
      "Shooting",
      "Stealth",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Concealed Position: When you set up this model during deployment, it can be set up anywhere on the battlefield that is more than 9\" away from any enemy deployment zone.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "captain-in-terminator-armour", name: "Captain in Terminator Armour", points: 80, maxNumber: "1", profile: { move: "5\"", ws: 2, bs: 2, strength: 4, toughness: 4, wounds: 6, attacks: 4, ld: 9, save: 2 }, keywords: "Space Marines, Imperium, Infantry, Terminator, Captain", wargear: "Combi-bolter; Wrist-mounted grenade launcher", specialisms: [
      "Ferocity",
      "Fortitude",
      "Leadership",
      "Logistics",
      "Melee",
      "Shooting",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "captain-with-master-crafted-heavy-bolt-rifle", name: "Captain with Master-crafted Heavy Bolt Rifle", points: 85, maxNumber: "1", profile: { move: "5\"", ws: 2, bs: 2, strength: 4, toughness: 5, wounds: 7, attacks: 5, ld: 9, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Primaris, Captain, Mk X Gravis", wargear: "Master-crafted heavy bolt rifle", specialisms: [
      "Ferocity",
      "Fortitude",
      "Leadership",
      "Logistics",
      "Melee",
      "Shooting",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "chaplain-in-terminator-armour", name: "Chaplain in Terminator Armour", points: 74, maxNumber: "1", profile: { move: "5\"", ws: 2, bs: 3, strength: 4, toughness: 4, wounds: 5, attacks: 3, ld: 9, save: 2 }, keywords: "Space Marines, Imperium, Infantry, Terminator, Chaplain", wargear: "", specialisms: [
      "Ferocity",
      "Fortitude",
      "Leadership",
      "Melee",
      "Shooting",
      "Strength"
    ], commander: true, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "company-veteran", name: "Company Veteran", points: 16, maxNumber: "4", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 8, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Company Veteran", wargear: "Boltgun", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "eliminator", name: "Eliminator", points: 18, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 2, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 7, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Phobos, Primaris, Eliminator", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "Concealed Position: When you set up this model during deployment, it can be set up anywhere on the battlefield that is more than 9\" away from any enemy deployment zone."
    ] },
  { key: "eliminator-sergeant", name: "Eliminator Sergeant", points: 19, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 2, strength: 4, toughness: 4, wounds: 2, attacks: 3, ld: 8, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Phobos, Primaris, Eliminator", wargear: "Instigator bolt carbine", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "Concealed Position: When you set up this model during deployment, it can be set up anywhere on the battlefield that is more than 9\" away from any enemy deployment zone."
    ] },
  { key: "heavy-intercessor", name: "Heavy Intercessor", points: 17, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 5, wounds: 3, attacks: 2, ld: 7, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Mk X Gravis, Primaris, Heavy Intercessor", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "heavy-intercessor-gunner", name: "Heavy Intercessor Gunner", points: 18, maxNumber: "2", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 5, wounds: 3, attacks: 2, ld: 7, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Mk X Gravis, Primaris, Heavy Intercessor", wargear: "Executor heavy bolter; Hellstorm heavy bolter", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "heavy-intercessor-sergeant", name: "Heavy Intercessor Sergeant", points: 18, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 5, wounds: 3, attacks: 3, ld: 8, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Mk X Gravis, Primaris, Heavy Intercessor", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "incursor", name: "Incursor", points: 16, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 7, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Phobos, Primaris, Incursor", wargear: "", specialisms: [], commander: false, abilities: [
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model."
    ] },
  { key: "incursor-sergeant", name: "Incursor Sergeant", points: 17, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 3, ld: 8, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Phobos, Primaris, Incursor", wargear: "", specialisms: [], commander: false, abilities: [
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model."
    ] },
  { key: "infiltrator", name: "Infiltrator", points: 17, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 7, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Phobos, Primaris, Infiltrator", wargear: "Infiltrator Comms Array", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "Concealed Position: When you set up this model during deployment, it can be set up anywhere on the battlefield that is more than 9\" away from any enemy deployment zone."
    ] },
  { key: "infiltrator-helix-adept", name: "Infiltrator Helix Adept", points: 18, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 7, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Phobos, Primaris, Infiltrator", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "Concealed Position: When you set up this model during deployment, it can be set up anywhere on the battlefield that is more than 9\" away from any enemy deployment zone."
    ] },
  { key: "infiltrator-sergeant", name: "Infiltrator Sergeant", points: 18, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 3, ld: 8, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Phobos, Primaris, Infiltrator", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "Concealed Position: When you set up this model during deployment, it can be set up anywhere on the battlefield that is more than 9\" away from any enemy deployment zone."
    ] },
  { key: "intercessor", name: "Intercessor", points: 15, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 7, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Primaris, Intercessor", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "intercessor-gunner", name: "Intercessor Gunner", points: 16, maxNumber: "2", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 7, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Primaris, Intercessor", wargear: "Auxiliary grenade launcher", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model."
    ] },
  { key: "intercessor-sergeant", name: "Intercessor Sergeant", points: 16, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 3, ld: 8, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Primaris, Intercessor", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "judiciar", name: "Judiciar", points: 73, maxNumber: "1", profile: { move: "6\"", ws: 2, bs: 3, strength: 4, toughness: 4, wounds: 5, attacks: 4, ld: 9, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Primaris, Judiciar", wargear: "Executioner relic blade", specialisms: [
      "Ferocity",
      "Fortitude",
      "Leadership",
      "Melee",
      "Shooting",
      "Strength"
    ], commander: true, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "librarian-in-phobos-armour", name: "Librarian in Phobos Armour", points: 89, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 5, attacks: 4, ld: 9, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Primaris, Librarian, Psyker, Phobos", wargear: "", specialisms: [
      "Fortitude",
      "Melee",
      "Psyker",
      "Stealth",
      "Strength"
    ], commander: true, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "Concealed Position: When you set up this model during deployment, it can be set up anywhere on the battlefield that is more than 9\" away from any enemy deployment zone."
    ] },
  { key: "librarian-in-terminator-armour", name: "Librarian in Terminator Armour", points: 88, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 5, attacks: 3, ld: 9, save: 2 }, keywords: "Space Marines, Imperium, Infantry, Terminator, Psyker, Librarian", wargear: "", specialisms: [
      "Fortitude",
      "Melee",
      "Psyker",
      "Shooting",
      "Strength"
    ], commander: true, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "lieutenant-in-phobos-armour", name: "Lieutenant in Phobos Armour", points: 51, maxNumber: "1", profile: { move: "6\"", ws: 2, bs: 3, strength: 4, toughness: 4, wounds: 5, attacks: 4, ld: 8, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Primaris, Grav-chute, Lieutenant, Phobos", wargear: "Master-crafted occulus bolt carbine", specialisms: [
      "Ferocity",
      "Fortitude",
      "Leadership",
      "Logistics",
      "Melee",
      "Shooting",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "lieutenant-in-reiver-armour", name: "Lieutenant in Reiver Armour", points: 51, maxNumber: "1", profile: { move: "6\"", ws: 2, bs: 2, strength: 4, toughness: 4, wounds: 5, attacks: 4, ld: 8, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Phobos, Primaris, Reiver, Lieutenant", wargear: "Master-crafted special issue bolt pistol", specialisms: [
      "Ferocity",
      "Fortitude",
      "Leadership",
      "Logistics",
      "Melee",
      "Shooting",
      "Stealth",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "Terror Troops: Subtract 1 from the Leadership characteristic of models while they are within 3\" of any enemy REIVER models."
    ] },
  { key: "primaris-captain", name: "Primaris Captain", points: 76, maxNumber: "1", profile: { move: "6\"", ws: 2, bs: 2, strength: 4, toughness: 4, wounds: 6, attacks: 5, ld: 9, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Captain, Primaris", wargear: "Heavy bolt pistol, master-crafted power sword and relic shield; Master-crafted auto bolt rifle and bolt pistol; Master-crafted stalker bolt rifle and bolt pistol; Plasma pistol and power fist; Relic shield", specialisms: [
      "Ferocity",
      "Fortitude",
      "Leadership",
      "Logistics",
      "Melee",
      "Shooting",
      "Stealth",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "primaris-chaplain", name: "Primaris Chaplain", points: 63, maxNumber: "1", profile: { move: "6\"", ws: 2, bs: 3, strength: 4, toughness: 4, wounds: 5, attacks: 4, ld: 9, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Chaplain, Primaris", wargear: "", specialisms: [
      "Ferocity",
      "Fortitude",
      "Leadership",
      "Melee",
      "Shooting",
      "Strength"
    ], commander: true, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "primaris-librarian", name: "Primaris Librarian", points: 81, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 5, attacks: 4, ld: 9, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Psyker, Librarian, Primaris", wargear: "", specialisms: [
      "Fortitude",
      "Melee",
      "Psyker",
      "Shooting",
      "Strength"
    ], commander: true, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "primaris-lieutenant", name: "Primaris Lieutenant", points: 46, maxNumber: "1", profile: { move: "6\"", ws: 2, bs: 3, strength: 4, toughness: 4, wounds: 5, attacks: 4, ld: 8, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Lieutenant, Primaris", wargear: "Master-crafted power axe; Neo-volkite pistol, master-crafted power sword and storm shield; Special-issue bolt carbine and master-crafted power axe", specialisms: [
      "Ferocity",
      "Fortitude",
      "Leadership",
      "Logistics",
      "Melee",
      "Shooting",
      "Stealth",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "reiver", name: "Reiver", points: 16, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 7, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Phobos, Primaris, Reiver", wargear: "", specialisms: [], commander: false, abilities: [
      "Terror Troops: Subtract 1 from the Leadership characteristic of models while they are within 3\" of any enemy REIVER models.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model."
    ] },
  { key: "reiver-sergeant", name: "Reiver Sergeant", points: 17, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 3, ld: 8, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Phobos, Primaris, Reiver", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "Terror Troops: Subtract 1 from the Leadership characteristic of models while they are within 3\" of any enemy REIVER models."
    ] },
  { key: "space-wolf-company-veteran", name: "Space Wolf Company Veteran", points: 16, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 8, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Company Veteran, Space Wolves", wargear: "Boltgun", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "space-wolf-terminator", name: "Space Wolf Terminator", points: 25, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 3, attacks: 2, ld: 8, save: 2 }, keywords: "Space Marines, Imperium, Infantry, Terminator, Space Wolves", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "space-wolf-terminator-gunner", name: "Space Wolf Terminator Gunner", points: 26, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 3, attacks: 2, ld: 8, save: 2 }, keywords: "Space Marines, Imperium, Infantry, Terminator, Space Wolves", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "space-wolf-terminator-sergeant", name: "Space Wolf Terminator Sergeant", points: 27, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 3, attacks: 2, ld: 8, save: 2 }, keywords: "Space Marines, Imperium, Infantry, Terminator, Space Wolves", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "sternguard-gunner", name: "Sternguard Gunner", points: 17, maxNumber: "2", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 8, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Sternguard Veteran", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "sternguard-sergeant", name: "Sternguard Sergeant", points: 17, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 3, ld: 9, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Sternguard Veteran", wargear: "Auspex; Special issue boltgun", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "sternguard-veteran", name: "Sternguard Veteran", points: 16, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 8, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Sternguard Veteran", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "suppressor", name: "Suppressor", points: 29, maxNumber: "-", profile: { move: "12\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 7, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Fly, Phobos, Primaris, Grav-chute, Suppressor", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "suppressor-sergeant", name: "Suppressor Sergeant", points: 30, maxNumber: "1", profile: { move: "12\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 3, ld: 8, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Fly, Phobos, Primaris, Grav-chute, Suppressor", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "terminator", name: "Terminator", points: 25, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 3, attacks: 2, ld: 8, save: 2 }, keywords: "Space Marines, Imperium, Infantry, Terminator", wargear: "Pair of lightning claws; Thunder hammer and Storm shield", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "terminator-gunner", name: "Terminator Gunner", points: 26, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 3, attacks: 2, ld: 8, save: 2 }, keywords: "Space Marines, Imperium, Infantry, Terminator", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "terminator-sergeant", name: "Terminator Sergeant", points: 27, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 3, attacks: 2, ld: 8, save: 2 }, keywords: "Space Marines, Imperium, Infantry, Terminator", wargear: "Pair of lightning claws; Thunder hammer and Storm shield", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "vanguard-sergeant", name: "Vanguard Sergeant", points: 17, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 3, ld: 9, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Vanguard Veteran", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "vanguard-veteran", name: "Vanguard Veteran", points: 16, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 8, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Vanguard Veteran", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "veteran-gunner", name: "Veteran Gunner", points: 17, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 8, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Company Veteran", wargear: "", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "veteran-sergeant", name: "Veteran Sergeant", points: 17, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 3, ld: 9, save: 3 }, keywords: "Space Marines, Imperium, Infantry, Company Veteran", wargear: "Boltgun", specialisms: [], commander: false, abilities: [
      "And They Shall Know No Fear: You can re-roll failed Nerve tests for this model.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] }
];

const FACTION = "Space Marines";

export const SPACE_MARINES_ITEMS = SPACE_MARINES_WEAPONS.map(w => ({ ...w, itemType: "weapon", faction: FACTION }));

export const SPACE_MARINES_MODEL_ITEMS = SPACE_MARINES_MODELS.map(m => ({ ...m, itemType: "model", faction: FACTION, rules: [] }));
