/**
 * Thousand Sons.
 *
 * Generated by tools/import_catalogue.py from the New Recruit catalogue,
 * which tracks Kill Team 2018 including errata and the Elites and Commanders
 * expansions. Do not hand-edit: re-run the importer instead.
 *
 * 11 models, 18 weapons.
 *
 * Ability text is imported as prose. Machine-readable rules are tagged
 * separately, by hand, in module/rules/ - deciding what an ability does is a
 * judgement call and is not safe to automate.
 */

export const THOUSAND_SONS_WEAPONS = [
  { key: "autopistol", name: "Autopistol", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "3", ap: 0, damage: "1", abilities: "" },
  { key: "frag-grenade", name: "Frag grenade", points: 0, range: "6\"", weaponType: "grenade", attacks: "D6", strength: "3", ap: 0, damage: "1", abilities: "" },
  { key: "heavy-warpflamer", name: "Heavy warpflamer", points: 0, range: "8\"", weaponType: "heavy", attacks: "D6", strength: "5", ap: -2, damage: "1", abilities: "" },
  { key: "hellfyre-missile-rack", name: "Hellfyre missile rack", points: 4, range: "24\"", weaponType: "heavy", attacks: "2", strength: "8", ap: -2, damage: "D3", abilities: "" },
  { key: "inferno-boltgun", name: "Inferno Boltgun", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "1", strength: "4", ap: -2, damage: "1", abilities: "" },
  { key: "inferno-bolt-pistol", name: "Inferno bolt pistol", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "4", ap: -2, damage: "1", abilities: "" },
  { key: "inferno-combi-bolter", name: "Inferno combi-bolter", points: 0, range: "24\"", weaponType: "rapidFire", attacks: "2", strength: "4", ap: -2, damage: "1", abilities: "" },
  { key: "krak-grenade", name: "Krak grenade", points: 0, range: "6\"", weaponType: "grenade", attacks: "1", strength: "6", ap: -1, damage: "D3", abilities: "" },
  { key: "plasma-pistol-standard", name: "Plasma pistol - Standard", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "7", ap: -3, damage: "1", abilities: "" },
  { key: "plasma-pistol-supercharge", name: "Plasma pistol - Supercharge", points: 0, range: "12\"", weaponType: "pistol", attacks: "1", strength: "8", ap: -3, damage: "2", abilities: "On an unmodified hit roll of 1, the bearer is taken out of action." },
  { key: "soulreaper-cannon", name: "Soulreaper Cannon", points: 4, range: "24\"", weaponType: "heavy", attacks: "4", strength: "5", ap: -3, damage: "1", abilities: "" },
  { key: "warpflame-pistol", name: "Warpflame pistol", points: 1, range: "6\"", weaponType: "pistol", attacks: "D6", strength: "3", ap: -2, damage: "1", abilities: "This weapon automatically hits its target." },
  { key: "warpflamer", name: "Warpflamer", points: 4, range: "8\"", weaponType: "assault", attacks: "D6", strength: "4", ap: -2, damage: "1", abilities: "This weapon automatically hits its target." },
  { key: "blades", name: "Blades", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "4", ap: 0, damage: "1", abilities: "After a model on this mount makes its close combat attacks, you can attack with its mount. Make 1 additional attack, using this weapon profile." },
  { key: "chainsword", name: "Chainsword", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "Each time the bearer fights, it can make 1 additional attack with this weapon." },
  { key: "force-stave", name: "Force stave", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "+2", ap: -1, damage: "D3", abilities: "" },
  { key: "power-sword", name: "Power sword", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -3, damage: "1", abilities: "" },
  { key: "tzaangor-blades", name: "Tzaangor blades", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "1", abilities: "Each time the bearer fights, it can make 1 additional attack with this weapon." }
];

export const THOUSAND_SONS_MODELS = [
  { key: "aspiring-sorcerer", name: "Aspiring Sorcerer", points: 17, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 1, attacks: 2, ld: 8, save: 3 }, keywords: "Thousand Sons, Chaos, Tzeentch, Heretic Astartes, Infantry, Psyker, Rubric Marine", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Veteran"
    ], commander: false, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Favoured of Tzeentch: This model has a 5+ invulnerable save.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "exalted-sorcerer", name: "Exalted Sorcerer", points: 81, maxNumber: "1", profile: { move: "6\"", ws: 2, bs: 2, strength: 4, toughness: 4, wounds: 5, attacks: 4, ld: 9, save: 3 }, keywords: "Thousand Sons, Chaos, Tzeentch, Heretic Astartes, Commander, Infantry, Sorcerer, Psyker, Exalted Sorcerer", wargear: "Plasma pistol", specialisms: [
      "Fortitude",
      "Leadership",
      "Logistics",
      "Melee",
      "Psyker",
      "Shooting",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "Favoured of Tzeentch: This model has a 5+ invulnerable save."
    ] },
  { key: "exalted-sorcerer-on-disc-of-tzeentch", name: "Exalted Sorcerer on Disc of Tzeentch", points: 81, maxNumber: "1", profile: { move: "12\"", ws: 2, bs: 2, strength: 4, toughness: 4, wounds: 5, attacks: 4, ld: 9, save: 3 }, keywords: "Thousand Sons, Chaos, Tzeentch, Heretic Astartes, Sorcerer, Psyker, Cavalry, Daemon, Fly, Exalted Sorcerer", wargear: "Blades; Disc of Tzeentch; Plasma pistol; Power sword", specialisms: [
      "Fortitude",
      "Leadership",
      "Logistics",
      "Melee",
      "Psyker",
      "Shooting",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered.",
      "Favoured of Tzeentch: This model has a 5+ invulnerable save."
    ] },
  { key: "rubric-marine", name: "Rubric Marine", points: 16, maxNumber: "-", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 1, attacks: 1, ld: 7, save: 3 }, keywords: "Thousand Sons, Chaos, Tzeentch, Heretic Astartes, Infantry, Rubric Marine", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Veteran"
    ], commander: false, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "All is Dust: Add 1 to saving throws for this model if the attack has a Damage characteristic of 1. In addition, the -1 modifier to hit rolls for moving and shooting Heavy weapons does not apply to Rubric Marine Gunners or Scarab Occult Gunners.",
      "Favoured of Tzeentch: This model has a 5+ invulnerable save."
    ] },
  { key: "rubric-marine-gunner", name: "Rubric Marine Gunner", points: 16, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 1, attacks: 1, ld: 7, save: 3 }, keywords: "Thousand Sons, Chaos, Tzeentch, Heretic Astartes, Infantry, Rubric Marine", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Heavy",
      "Veteran"
    ], commander: false, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "All is Dust: Add 1 to saving throws for this model if the attack has a Damage characteristic of 1. In addition, the -1 modifier to hit rolls for moving and shooting Heavy weapons does not apply to Rubric Marine Gunners or Scarab Occult Gunners.",
      "Favoured of Tzeentch: This model has a 5+ invulnerable save."
    ] },
  { key: "scarab-occult-gunner", name: "Scarab Occult Gunner", points: 33, maxNumber: "-", profile: { move: "4\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 8, save: 2 }, keywords: "Thousand Sons, Chaos, Tzeentch, Heretic Astartes, Infantry, Terminator, Scarab Occult Terminator", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Heavy",
      "Veteran"
    ], commander: false, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "All is Dust: Add 1 to saving throws for this model if the attack has a Damage characteristic of 1. In addition, the -1 modifier to hit rolls for moving and shooting Heavy weapons does not apply to Rubric Marine Gunners or Scarab Occult Gunners.",
      "Terminator Armour: This model has a 5+ invulnerable save."
    ] },
  { key: "scarab-occult-sorcerer", name: "Scarab Occult Sorcerer", points: 38, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 9, save: 2 }, keywords: "Thousand Sons, Chaos, Tzeentch, Heretic Astartes, Infantry, Terminator, Scarab Occult Terminator, Psyker", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Veteran"
    ], commander: false, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "Terminator Armour: This model has a 5+ invulnerable save.",
      "Transhuman Physiology: Ignore the penalty to this model's hit rolls from one flesh wound it has suffered."
    ] },
  { key: "scarab-occult-terminator", name: "Scarab Occult Terminator", points: 32, maxNumber: "-", profile: { move: "4\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 2, attacks: 2, ld: 8, save: 2 }, keywords: "Thousand Sons, Chaos, Tzeentch, Heretic Astartes, Infantry, Terminator, Scarab Occult Terminator", wargear: "", specialisms: [
      "Combat",
      "Demolitions",
      "Veteran"
    ], commander: false, abilities: [
      "Death to the False Emperor: If a model with this ability makes an attack in the Fight phase which targets an IMPERIUM model, each time you roll a hit roll of 6+ you may make an additional attack with the same weapon against the same target. These attacks cannot themselves generate any further attacks.",
      "All is Dust: Add 1 to saving throws for this model if the attack has a Damage characteristic of 1. In addition, the -1 modifier to hit rolls for moving and shooting Heavy weapons does not apply to Rubric Marine Gunners or Scarab Occult Gunners.",
      "Terminator Armour: This model has a 5+ invulnerable save."
    ] },
  { key: "twistbray", name: "Twistbray", points: 8, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 4, strength: 4, toughness: 4, wounds: 1, attacks: 2, ld: 7, save: 6 }, keywords: "Thousand Sons, Chaos, Tzeentch, Heretic Astartes, Infantry, Tzaangor", wargear: "Autopistol and chainsword", specialisms: [
      "Combat",
      "Demolitions",
      "Medic",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Aura of Dark Glory: This model has a 5+ invulnerable save."
    ] },
  { key: "tzaangor", name: "Tzaangor", points: 7, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 4, strength: 4, toughness: 4, wounds: 1, attacks: 1, ld: 6, save: 6 }, keywords: "Thousand Sons, Chaos, Tzeentch, Heretic Astartes, Infantry, Tzaangor", wargear: "Autopistol and chainsword", specialisms: [
      "Combat",
      "Comms",
      "Demolitions",
      "Medic",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Aura of Dark Glory: This model has a 5+ invulnerable save."
    ] },
  { key: "tzaangor-shaman", name: "Tzaangor Shaman", points: 40, maxNumber: "1", profile: { move: "12\"", ws: 3, bs: 3, strength: 4, toughness: 4, wounds: 4, attacks: 3, ld: 8, save: 6 }, keywords: "Thousand Sons, Chaos, Tzeentch, Heretic Astartes, Cavalry, Daemon, Tzaangor, Fly, Psyker, Shaman", wargear: "Blades; Disc of Tzeentch", specialisms: [
      "Ferocity",
      "Fortitude",
      "Leadership",
      "Melee",
      "Psyker",
      "Strategist",
      "Strength"
    ], commander: true, abilities: [
      "Aura of Dark Glory: This model has a 5+ invulnerable save."
    ] }
];

const FACTION = "Thousand Sons";

export const THOUSAND_SONS_ITEMS = THOUSAND_SONS_WEAPONS.map(w => ({ ...w, itemType: "weapon", faction: FACTION }));

export const THOUSAND_SONS_MODEL_ITEMS = THOUSAND_SONS_MODELS.map(m => ({ ...m, itemType: "model", faction: FACTION, rules: [] }));
