/**
 * Tyranids.
 *
 * Generated by tools/import_catalogue.py from the New Recruit catalogue,
 * which tracks Kill Team 2018 including errata and the Elites and Commanders
 * expansions. Do not hand-edit: re-run the importer instead.
 *
 * 13 models, 17 weapons.
 *
 * Ability text is imported as prose. Machine-readable rules are tagged
 * separately, by hand, in module/rules/ - deciding what an ability does is a
 * judgement call and is not safe to automate.
 */

export const TYRANIDS_WEAPONS = [
  { key: "barbed-strangler", name: "Barbed strangler", points: 3, range: "36\"", weaponType: "assault", attacks: "D6", strength: "5", ap: -1, damage: "1", abilities: "" },
  { key: "deathspitter", name: "Deathspitter", points: 2, range: "24\"", weaponType: "assault", attacks: "3", strength: "5", ap: -1, damage: "1", abilities: "" },
  { key: "devourer", name: "Devourer", points: 0, range: "18\"", weaponType: "assault", attacks: "3", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "flesh-hooks", name: "Flesh hooks", points: 0, range: "6\"", weaponType: "assault", attacks: "2", strength: "User", ap: 0, damage: "1", abilities: "The weapon can be fired within 1\" of an enemy model, and can target enemy models within 1\" of friendly models." },
  { key: "fleshborer", name: "Fleshborer", points: 0, range: "12\"", weaponType: "assault", attacks: "1", strength: "4", ap: 0, damage: "1", abilities: "" },
  { key: "impaler-cannon", name: "Impaler cannon", points: 0, range: "36\"", weaponType: "heavy", attacks: "2", strength: "8", ap: -2, damage: "D3", abilities: "This weapon can be fired at models that are not visible to the bearer. If the target is not visible to the bearer, a 6 is required for a successful hit roll, irrespective of the firing model\u2019s Ballistic Skill or any modifiers." },
  { key: "shockcannon", name: "Shockcannon", points: 0, range: "36\"", weaponType: "assault", attacks: "D3", strength: "7", ap: -1, damage: "D3", abilities: "" },
  { key: "spinefists", name: "Spinefists", points: 0, range: "12\"", weaponType: "pistol", attacks: "*", strength: "3", ap: 0, damage: "1", abilities: "When a model fires this weapon, it makes a number of shots equal to its Attacks characteristic." },
  { key: "venom-cannon", name: "Venom cannon", points: 4, range: "36\"", weaponType: "assault", attacks: "D3", strength: "8", ap: -2, damage: "D3", abilities: "" },
  { key: "acid-maw", name: "Acid Maw", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -3, damage: "1", abilities: "" },
  { key: "boneswords", name: "Boneswords", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -2, damage: "1", abilities: "A model armed with boneswords can make 1 additional attack with them in the Fight phase." },
  { key: "crushing-claws", name: "Crushing claws", points: 7, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -3, damage: "D3", abilities: "When attacking with this weapon, you must subtract 1 from the hit roll." },
  { key: "grasping-talons", name: "Grasping talons", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "2", abilities: "" },
  { key: "lash-whip-and-bonesword", name: "Lash whip and bonesword", points: 1, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -2, damage: "1", abilities: "If the bearer is taken out of action in the Fight phase before it has made its attacks in that phase, it may immediately fight before being removed from the battlefield." },
  { key: "monstrous-rending-claws", name: "Monstrous rending claws", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -3, damage: "D3", abilities: "You can re-roll failed wound rolls for this weapon. In addition, each time you make a wound roll of 6+, that hit is resolved with an AP of -6 and Damage of 3." },
  { key: "rending-claws", name: "Rending claws", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -1, damage: "1", abilities: "Each time you make a wound roll of 6+ for this weapon, that hit is resolved with an AP of -4." },
  { key: "scything-talons", name: "Scything talons", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "You can re-roll hit rolls of 1 for this weapon. If the bearer has more than one pair of scything talons, it can make 1 additional attack with them each time it fights." }
];

export const TYRANIDS_MODELS = [
  { key: "broodlord", name: "Broodlord", points: 131, maxNumber: "1", profile: { move: "8\"", ws: 2, bs: 4, strength: 5, toughness: 5, wounds: 6, attacks: 6, ld: 10, save: 4 }, keywords: "Tyranids, Infantry, Commander, Broodlord, Synapse, Psyker", wargear: "", specialisms: [], commander: true, abilities: [
      "Shadow in the Warp: Subract 1 from any psychic tests made for enemy PSKYERS within 18\" of a model with this ability. TYRANIDS PSYKERS are not affected.",
      "Synapse: TYRANIDS models automatically pass Nerve tests while they are within 12\" of any friendly models with this ability."
    ] },
  { key: "deathleaper", name: "Deathleaper", points: 70, maxNumber: "1", profile: { move: "9\"", ws: 2, bs: 4, strength: 6, toughness: 4, wounds: 6, attacks: 4, ld: 10, save: 5 }, keywords: "Tyranids, Infantry, Lictor, Deathleaper", wargear: "", specialisms: [], commander: false, abilities: [] },
  { key: "genestealer", name: "Genestealer", points: 11, maxNumber: "-", profile: { move: "8\"", ws: 3, bs: 4, strength: 4, toughness: 4, wounds: 1, attacks: 3, ld: 9, save: 5 }, keywords: "Tyranids, Infantry, Genestealer", wargear: "Extended Carapace; Flesh Hooks", specialisms: [
      "Combat",
      "Scout",
      "Veteran"
    ], commander: false, abilities: [] },
  { key: "hive-guard", name: "Hive Guard", points: 35, maxNumber: "-", profile: { move: "5\"", ws: 4, bs: 3, strength: 4, toughness: 5, wounds: 3, attacks: 2, ld: 7, save: 4 }, keywords: "Tyranids, Infantry, Hive Guard", wargear: "Impaler cannon; Shockcannon", specialisms: [
      "Heavy",
      "Sniper",
      "Veteran"
    ], commander: false, abilities: [
      "Instinctive Behaviour: Unless this model is within 24\" of a friendly SYNAPSE model, you must subtract 1 from any hit rolls made for it when shooting any target other than the nearest visible enemy model, and subtract 2 from any charge rolls made for it if it declares a charge against any model other than the nearest enemy model."
    ] },
  { key: "hormagaunt", name: "Hormagaunt", points: 4, maxNumber: "-", profile: { move: "8\"", ws: 4, bs: 4, strength: 3, toughness: 3, wounds: 1, attacks: 2, ld: 5, save: 6 }, keywords: "Tyranids, Infantry, Hormagaunt", wargear: "", specialisms: [
      "Combat",
      "Scout",
      "Veteran"
    ], commander: false, abilities: [
      "Instinctive Behaviour: Unless this model is within 24\" of a friendly SYNAPSE model, you must subtract 1 from any hit rolls made for it when shooting any target other than the nearest visible enemy model, and subtract 2 from any charge rolls made for it if it declares a charge against any model other than the nearest enemy model."
    ] },
  { key: "lictor", name: "Lictor", points: 25, maxNumber: "-", profile: { move: "9\"", ws: 2, bs: 4, strength: 6, toughness: 4, wounds: 4, attacks: 3, ld: 9, save: 5 }, keywords: "Tyranids, Infantry, Lictor", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Scout",
      "Veteran"
    ], commander: false, abilities: [] },
  { key: "nemesis-9-tyrantis", name: "Nemesis 9 Tyrantis", points: 131, maxNumber: "1", profile: { move: "8\"", ws: 2, bs: 4, strength: 5, toughness: 5, wounds: 6, attacks: 7, ld: 10, save: 4 }, keywords: "Tyranids, Commander, Infantry, Psyker, Synapse, Broodlord, Level 1, Level 2, Level 3, Level 4", wargear: "Level 1 - Voracious; Level 2 - Omnipresent Infamy; Level 3 - Feed on Minds; Level 4 - Sow Fear and Death", specialisms: [], commander: true, abilities: [
      "Shadow in the Warp: Subract 1 from any psychic tests made for enemy PSKYERS within 18\" of a model with this ability. TYRANIDS PSYKERS are not affected.",
      "Synapse: TYRANIDS models automatically pass Nerve tests while they are within 12\" of any friendly models with this ability."
    ] },
  { key: "ravener", name: "Ravener", points: 15, maxNumber: "-", profile: { move: "12\"", ws: 3, bs: 4, strength: 4, toughness: 4, wounds: 3, attacks: 4, ld: 5, save: 5 }, keywords: "Tyranids, Infantry, Ravener", wargear: "", specialisms: [
      "Combat",
      "Scout",
      "Veteran"
    ], commander: false, abilities: [
      "Instinctive Behaviour: Unless this model is within 24\" of a friendly SYNAPSE model, you must subtract 1 from any hit rolls made for it when shooting any target other than the nearest visible enemy model, and subtract 2 from any charge rolls made for it if it declares a charge against any model other than the nearest enemy model."
    ] },
  { key: "termagant", name: "Termagant", points: 4, maxNumber: "-", profile: { move: "6\"", ws: 4, bs: 4, strength: 3, toughness: 3, wounds: 1, attacks: 1, ld: 5, save: 6 }, keywords: "Tyranids, Infantry, Termagant", wargear: "", specialisms: [
      "Scout",
      "Veteran"
    ], commander: false, abilities: [
      "Instinctive Behaviour: Unless this model is within 24\" of a friendly SYNAPSE model, you must subtract 1 from any hit rolls made for it when shooting any target other than the nearest visible enemy model, and subtract 2 from any charge rolls made for it if it declares a charge against any model other than the nearest enemy model."
    ] },
  { key: "tyranid-prime", name: "Tyranid Prime", points: 50, maxNumber: "1", profile: { move: "6\"", ws: 2, bs: 3, strength: 5, toughness: 5, wounds: 6, attacks: 4, ld: 10, save: 3 }, keywords: "Tyranids, Infantry, Synapse, Commander, Tyranid Prime", wargear: "", specialisms: [], commander: true, abilities: [
      "Synapse: TYRANIDS models automatically pass Nerve tests while they are within 12\" of any friendly models with this ability.",
      "Shadow in the Warp: Subract 1 from any psychic tests made for enemy PSKYERS within 18\" of a model with this ability. TYRANIDS PSYKERS are not affected."
    ] },
  { key: "tyranid-warrior", name: "Tyranid Warrior", points: 20, maxNumber: "-", profile: { move: "6\"", ws: 3, bs: 4, strength: 4, toughness: 4, wounds: 3, attacks: 3, ld: 9, save: 4 }, keywords: "Tyranids, Infantry, Synapse, Tyranid Warrior", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Veteran"
    ], commander: false, abilities: [
      "Synapse: TYRANIDS models automatically pass Nerve tests while they are within 12\" of any friendly models with this ability.",
      "Shadow in the Warp: Subract 1 from any psychic tests made for enemy PSKYERS within 18\" of a model with this ability. TYRANIDS PSYKERS are not affected."
    ] },
  { key: "tyranid-warrior-gunner", name: "Tyranid Warrior Gunner", points: 20, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 4, strength: 4, toughness: 4, wounds: 3, attacks: 3, ld: 9, save: 4 }, keywords: "Tyranids, Infantry, Synapse, Tyranid Warrior", wargear: "", specialisms: [
      "Combat",
      "Comms",
      "Heavy",
      "Veteran"
    ], commander: false, abilities: [
      "Synapse: TYRANIDS models automatically pass Nerve tests while they are within 12\" of any friendly models with this ability.",
      "Shadow in the Warp: Subract 1 from any psychic tests made for enemy PSKYERS within 18\" of a model with this ability. TYRANIDS PSYKERS are not affected."
    ] },
  { key: "tyrant-guard", name: "Tyrant Guard", points: 32, maxNumber: "-", profile: { move: "7\"", ws: 3, bs: 4, strength: 5, toughness: 5, wounds: 3, attacks: 3, ld: 6, save: 3 }, keywords: "Tyranids, Infantry, Tyrant Guard", wargear: "Crushing claws", specialisms: [
      "Combat",
      "Veteran",
      "Zealot"
    ], commander: false, abilities: [
      "Instinctive Behaviour: Unless this model is within 24\" of a friendly SYNAPSE model, you must subtract 1 from any hit rolls made for it when shooting any target other than the nearest visible enemy model, and subtract 2 from any charge rolls made for it if it declares a charge against any model other than the nearest enemy model."
    ] }
];

const FACTION = "Tyranids";

export const TYRANIDS_ITEMS = TYRANIDS_WEAPONS.map(w => ({ ...w, itemType: "weapon", faction: FACTION }));

export const TYRANIDS_MODEL_ITEMS = TYRANIDS_MODELS.map(m => ({ ...m, itemType: "model", faction: FACTION, rules: [] }));
