/**
 * Unaligned.
 *
 * Generated by tools/import_catalogue.py from the New Recruit catalogue,
 * which tracks Kill Team 2018 including errata and the Elites and Commanders
 * expansions. Do not hand-edit: re-run the importer instead.
 *
 * 3 models, 4 weapons.
 *
 * Ability text is imported as prose. Machine-readable rules are tagged
 * separately, by hand, in module/rules/ - deciding what an ability does is a
 * judgement call and is not safe to automate.
 */

export const UNALIGNED_WEAPONS = [
  { key: "atomic-disassembler", name: "Atomic disassembler", points: 0, range: "18\"", weaponType: "pistol", attacks: "1", strength: "8", ap: -3, damage: "D6", abilities: "Attacks made with this weapon do not suffer the penalty to hit rolls and injury rolls for the target being obscured." },
  { key: "enormous-claws", name: "Enormous Claws", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: -3, damage: "D3", abilities: "" },
  { key: "eradicator-glove", name: "Eradicator glove", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "x2", ap: -3, damage: "3", abilities: "When attacking with this weapon, you must subtract 1 from the hit roll." },
  { key: "vicious-jaws", name: "Vicious jaws", points: 0, range: "Melee", weaponType: "melee", attacks: "1", strength: "User", ap: 0, damage: "1", abilities: "Each time you make a wound roll of 6+ for this weapon, that hit is resolved at AP -2 instead." }
];

export const UNALIGNED_MODELS = [
  { key: "ambull", name: "Ambull", points: 0, maxNumber: "1", profile: { move: "6\"", ws: 3, bs: 6, strength: 6, toughness: 6, wounds: 7, attacks: 4, ld: 6, save: 3 }, keywords: "Unaligned, Monster, Ambull", wargear: "Enormous Claws", specialisms: [], commander: false, abilities: [] },
  { key: "borewyrm-infestation", name: "Borewyrm Infestation", points: 0, maxNumber: "2", profile: { move: "4\"", ws: 4, bs: 6, strength: 3, toughness: 4, wounds: 2, attacks: 3, ld: 5, save: 4 }, keywords: "Unaligned", wargear: "Vicious jaws", specialisms: [], commander: false, abilities: [] },
  { key: "the-archivist", name: "The Archivist", points: 0, maxNumber: "1", profile: { move: "5\"", ws: 3, bs: 3, strength: 5, toughness: 4, wounds: 6, attacks: 4, ld: 9, save: 3 }, keywords: "Unaligned, Monster, The Archivist", wargear: "Atomic disassembler; Eradicator glove", specialisms: [], commander: false, abilities: [] }
];

const FACTION = "Unaligned";

export const UNALIGNED_ITEMS = UNALIGNED_WEAPONS.map(w => ({ ...w, itemType: "weapon", faction: FACTION }));

export const UNALIGNED_MODEL_ITEMS = UNALIGNED_MODELS.map(m => ({ ...m, itemType: "model", faction: FACTION, rules: [] }));
